//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTA_ADEUDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALTA_ADEUDO()
        {
            this.ALTA_ADEUDO_TITULAR = new HashSet<ALTA_ADEUDO_TITULAR>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_ADEUDO { get; set; }
        public int NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public string V_LUGAR { get; set; }
        public int NID_INSTITUCION { get; set; }
        public string V_OTRA { get; set; }
        public int NID_TIPO_ADEUDO { get; set; }
        public System.DateTime F_ADEUDO { get; set; }
        public decimal M_ORIGINAL { get; set; }
        public decimal M_SALDO { get; set; }
        public string E_CUENTA { get; set; }
        public bool L_AUTOGENERADO { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public string V_TIPO_MONEDA { get; set; }
        public string CID_TIPO_PERSONA_OTORGANTE { get; set; }
        public string E_RFC { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
        public string NID_TERCERO { get; set; }
        public string E_NOMBRE_TERCERO { get; set; }
        public string E_RFC_TERCERO { get; set; }
    
        public virtual ALTA ALTA { get; set; }
        public virtual CAT_TIPO_ADEUDO CAT_TIPO_ADEUDO { get; set; }
        public virtual CAT_ESTADO_TESTADO CAT_ESTADO_TESTADO { get; set; }
        public virtual ALTA_ADEUDO_PAGOS ALTA_ADEUDO_PAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_ADEUDO_TITULAR> ALTA_ADEUDO_TITULAR { get; set; }
        public virtual CAT_ENTIDAD_FEDERATIVA CAT_ENTIDAD_FEDERATIVA { get; set; }
        public virtual CAT_INST_FINANCIERA CAT_INST_FINANCIERA { get; set; }
    }
}
