//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTA_COMODATO
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_COMODATO { get; set; }
        public string CID_TIPO_PERSONA { get; set; }
        public string E_TITULAR { get; set; }
        public string E_RFC { get; set; }
        public int NID_TIPO_RELACION { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
    
        public virtual ALTA ALTA { get; set; }
        public virtual ALTA_COMODATO_INMUEBLE ALTA_COMODATO_INMUEBLE { get; set; }
        public virtual ALTA_COMODATO_VEHICULO ALTA_COMODATO_VEHICULO { get; set; }
    }
}
