//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTA_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALTA_VEHICULO()
        {
            this.ALTA_VEHICULO_COPROPIETARIO = new HashSet<ALTA_VEHICULO_COPROPIETARIO>();
            this.ALTA_VEHICULO_TITULAR = new HashSet<ALTA_VEHICULO_TITULAR>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_VEHICULO { get; set; }
        public int NID_MARCA { get; set; }
        public string C_MODELO { get; set; }
        public string V_DESCRIPCION { get; set; }
        public System.DateTime F_ADQUISICION { get; set; }
        public int NID_TIPO_VEHICULO { get; set; }
        public int NID_USO { get; set; }
        public decimal M_VALOR_VEHICULO { get; set; }
        public string V_TIPO_MONEDA { get; set; }
        public string E_NUMERO_SERIE { get; set; }
        public Nullable<int> NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public string CID_TIPO_PERSONA_TRANSMISOR { get; set; }
        public string E_NOMBRE_TRANSMISOR { get; set; }
        public string E_RFC_TRANSMISOR { get; set; }
        public int NID_RELACION_TRANSMISOR { get; set; }
        public Nullable<int> NID_FORMA_ADQUISICION { get; set; }
        public Nullable<int> NID_FORMA_PAGO { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
    
        public virtual ALTA ALTA { get; set; }
        public virtual ALTA_VEHICULO_ADEUDO ALTA_VEHICULO_ADEUDO { get; set; }
        public virtual CAT_ENTIDAD_FEDERATIVA CAT_ENTIDAD_FEDERATIVA { get; set; }
        public virtual CAT_ESTADO_TESTADO CAT_ESTADO_TESTADO { get; set; }
        public virtual CAT_FORMA_ADQUISICION CAT_FORMA_ADQUISICION { get; set; }
        public virtual CAT_FORMA_PAGO CAT_FORMA_PAGO { get; set; }
        public virtual CAT_RELACION_TRANSMISOR CAT_RELACION_TRANSMISOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_VEHICULO_COPROPIETARIO> ALTA_VEHICULO_COPROPIETARIO { get; set; }
        public virtual ALTA_VEHICULO_FORMA_ADQUISICION ALTA_VEHICULO_FORMA_ADQUISICION { get; set; }
        public virtual ALTA_VEHICULO_PAGO_INICIAL ALTA_VEHICULO_PAGO_INICIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_VEHICULO_TITULAR> ALTA_VEHICULO_TITULAR { get; set; }
        public virtual CAT_MARCA_VEHICULO CAT_MARCA_VEHICULO { get; set; }
        public virtual CAT_USO_VEHICULO CAT_USO_VEHICULO { get; set; }
        public virtual CAT_TIPO_VEHICULO CAT_TIPO_VEHICULO { get; set; }
    }
}
