//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTA_INVERSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALTA_INVERSION()
        {
            this.ALTA_INVERSION_COPROPIETARIO = new HashSet<ALTA_INVERSION_COPROPIETARIO>();
            this.ALTA_INVERSION_TITULAR = new HashSet<ALTA_INVERSION_TITULAR>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_INVERSION { get; set; }
        public int NID_TIPO_INVERSION { get; set; }
        public int NID_SUBTIPO_INVERSION { get; set; }
        public int NID_INSTITUCION { get; set; }
        public string E_CUENTA { get; set; }
        public string V_CUENTA_CORTO { get; set; }
        public string V_OTRO { get; set; }
        public decimal M_SALDO { get; set; }
        public int NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public string V_LUGAR { get; set; }
        public System.DateTime F_APERTURA { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public string V_RFC_INVERSION { get; set; }
        public string V_TIPO_MONEDA { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
    
        public virtual ALTA ALTA { get; set; }
        public virtual CAT_ESTADO_TESTADO CAT_ESTADO_TESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INVERSION_COPROPIETARIO> ALTA_INVERSION_COPROPIETARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INVERSION_TITULAR> ALTA_INVERSION_TITULAR { get; set; }
        public virtual CAT_SUBTIPO_INVERSION CAT_SUBTIPO_INVERSION { get; set; }
        public virtual CAT_INST_FINANCIERA CAT_INST_FINANCIERA { get; set; }
        public virtual CAT_ENTIDAD_FEDERATIVA CAT_ENTIDAD_FEDERATIVA { get; set; }
    }
}
