//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALTA_INMUEBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALTA_INMUEBLE()
        {
            this.ALTA_INMUEBLE_ADEUDO = new HashSet<ALTA_INMUEBLE_ADEUDO>();
            this.ALTA_INMUEBLE_COPROPIETARIO = new HashSet<ALTA_INMUEBLE_COPROPIETARIO>();
            this.ALTA_INMUEBLE_TITULAR = new HashSet<ALTA_INMUEBLE_TITULAR>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_INMUEBLE { get; set; }
        public int NID_TIPO { get; set; }
        public System.DateTime F_ADQUISICION { get; set; }
        public int NID_USO { get; set; }
        public string E_UBICACION { get; set; }
        public decimal N_TERRENO { get; set; }
        public decimal N_CONSTRUCCION { get; set; }
        public decimal M_VALOR_INMUEBLE { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public decimal N_PORCENTAJE_DECLARANTE { get; set; }
        public string E_REGISTRO_PUBLICO_PROPIEDAD { get; set; }
        public string CID_TIPO_PERSONA_TRANSMISOR { get; set; }
        public string E_NOMBRE_TRANSMISOR { get; set; }
        public string E_RFC_TRANSMISOR { get; set; }
        public int NID_RELACION_TRANSMISOR { get; set; }
        public string V_TIPO_MONEDA { get; set; }
        public int NID_VALOR_ADQUISICION { get; set; }
        public Nullable<int> NID_FORMA_ADQUISICION { get; set; }
        public Nullable<int> NID_FORMA_PAGO { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
    
        public virtual ALTA ALTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INMUEBLE_ADEUDO> ALTA_INMUEBLE_ADEUDO { get; set; }
        public virtual CAT_ESTADO_TESTADO CAT_ESTADO_TESTADO { get; set; }
        public virtual CAT_FORMA_ADQUISICION CAT_FORMA_ADQUISICION { get; set; }
        public virtual CAT_FORMA_PAGO CAT_FORMA_PAGO { get; set; }
        public virtual CAT_RELACION_TRANSMISOR CAT_RELACION_TRANSMISOR { get; set; }
        public virtual CAT_VALOR_ADQUISICION CAT_VALOR_ADQUISICION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INMUEBLE_COPROPIETARIO> ALTA_INMUEBLE_COPROPIETARIO { get; set; }
        public virtual ALTA_INMUEBLE_FORMA_ADQUISICION ALTA_INMUEBLE_FORMA_ADQUISICION { get; set; }
        public virtual ALTA_INMUEBLE_PAGO_INICIAL ALTA_INMUEBLE_PAGO_INICIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INMUEBLE_TITULAR> ALTA_INMUEBLE_TITULAR { get; set; }
        public virtual CAT_TIPO_INMUEBLE CAT_TIPO_INMUEBLE { get; set; }
        public virtual CAT_USO_INMUEBLE CAT_USO_INMUEBLE { get; set; }
    }
}
