//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPO_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TIPO_VEHICULO()
        {
            this.ALTA_COMODATO_VEHICULO = new HashSet<ALTA_COMODATO_VEHICULO>();
            this.ALTA_VEHICULO = new HashSet<ALTA_VEHICULO>();
        }
    
        public int NID_TIPO_VEHICULO { get; set; }
        public string V_TIPO_VEHICULO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_COMODATO_VEHICULO> ALTA_COMODATO_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_VEHICULO> ALTA_VEHICULO { get; set; }
    }
}
