//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPO_ADEUDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TIPO_ADEUDO()
        {
            this.ALTA_ADEUDO = new HashSet<ALTA_ADEUDO>();
            this.H_PATRIMONIO_ADEUDO = new HashSet<H_PATRIMONIO_ADEUDO>();
            this.PATRIMONIO_ADEUDO = new HashSet<PATRIMONIO_ADEUDO>();
        }
    
        public int NID_TIPO_ADEUDO { get; set; }
        public string V_TIPO_ADEUDO { get; set; }
        public bool L_ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_ADEUDO> ALTA_ADEUDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<H_PATRIMONIO_ADEUDO> H_PATRIMONIO_ADEUDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATRIMONIO_ADEUDO> PATRIMONIO_ADEUDO { get; set; }
    }
}
