//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_SECTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_SECTOR()
        {
            this.DECLARACION_DEPENDIENTES_PRIVADO = new HashSet<DECLARACION_DEPENDIENTES_PRIVADO>();
            this.DECLARACION_EXPERIENCIA_LABORAL = new HashSet<DECLARACION_EXPERIENCIA_LABORAL>();
        }
    
        public int NID_SECTOR { get; set; }
        public string V_SECTOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_DEPENDIENTES_PRIVADO> DECLARACION_DEPENDIENTES_PRIVADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_EXPERIENCIA_LABORAL> DECLARACION_EXPERIENCIA_LABORAL { get; set; }
    }
}
