//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CONFLICTO_PREGUNTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_CONFLICTO_PREGUNTA()
        {
            this.CONFLICTO_RESPUESTA = new HashSet<CONFLICTO_RESPUESTA>();
        }
    
        public int NID_RUBRO { get; set; }
        public int NID_PREGUNTA { get; set; }
        public string V_RUBRO { get; set; }
        public string V_OPCIONES { get; set; }
        public string C_INICIO { get; set; }
        public string C_FIN { get; set; }
        public bool L_TESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFLICTO_RESPUESTA> CONFLICTO_RESPUESTA { get; set; }
    }
}
