//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPO_MUEBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TIPO_MUEBLE()
        {
            this.ALTA_MUEBLE = new HashSet<ALTA_MUEBLE>();
            this.H_PATRIMONIO_MUEBLE = new HashSet<H_PATRIMONIO_MUEBLE>();
            this.MODIFICACION_MUEBLE = new HashSet<MODIFICACION_MUEBLE>();
            this.PATRIMONIO_MUEBLE = new HashSet<PATRIMONIO_MUEBLE>();
        }
    
        public int NID_TIPO { get; set; }
        public string V_TIPO { get; set; }
        public bool L_ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_MUEBLE> ALTA_MUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<H_PATRIMONIO_MUEBLE> H_PATRIMONIO_MUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_MUEBLE> MODIFICACION_MUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATRIMONIO_MUEBLE> PATRIMONIO_MUEBLE { get; set; }
    }
}
