//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PAIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_PAIS()
        {
            this.CAT_ENTIDAD_FEDERATIVA = new HashSet<CAT_ENTIDAD_FEDERATIVA>();
            this.DECLARACION_ESCOLARIDAD = new HashSet<DECLARACION_ESCOLARIDAD>();
            this.DECLARACION_EXPERIENCIA_LABORAL = new HashSet<DECLARACION_EXPERIENCIA_LABORAL>();
        }
    
        public int NID_PAIS { get; set; }
        public string V_PAIS { get; set; }
        public string V_NACIONALIDAD_M { get; set; }
        public string V_NACIONALIDAD_F { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_ENTIDAD_FEDERATIVA> CAT_ENTIDAD_FEDERATIVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_ESCOLARIDAD> DECLARACION_ESCOLARIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_EXPERIENCIA_LABORAL> DECLARACION_EXPERIENCIA_LABORAL { get; set; }
    }
}
