//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_DOCUMENTO_OBTENIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_DOCUMENTO_OBTENIDO()
        {
            this.DECLARACION_ESCOLARIDAD = new HashSet<DECLARACION_ESCOLARIDAD>();
        }
    
        public int NID_DOCUMENTO_OBTENIDO { get; set; }
        public string V_DOCUMENTO_OBTENIDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_ESCOLARIDAD> DECLARACION_ESCOLARIDAD { get; set; }
    }
}
