//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_USO_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_USO_VEHICULO()
        {
            this.ALTA_VEHICULO = new HashSet<ALTA_VEHICULO>();
            this.H_PATRIMONIO_VEHICULO = new HashSet<H_PATRIMONIO_VEHICULO>();
            this.MODIFICACION_VEHICULO = new HashSet<MODIFICACION_VEHICULO>();
            this.PATRIMONIO_VEHICULO = new HashSet<PATRIMONIO_VEHICULO>();
        }
    
        public int NID_USO { get; set; }
        public string V_USO { get; set; }
        public bool L_ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_VEHICULO> ALTA_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<H_PATRIMONIO_VEHICULO> H_PATRIMONIO_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_VEHICULO> MODIFICACION_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATRIMONIO_VEHICULO> PATRIMONIO_VEHICULO { get; set; }
    }
}
