//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_SECCION_INGRESO
    {
        public int NID_SECCION { get; set; }
        public int NID_RUBRO { get; set; }
        public string V_RUBRO { get; set; }
        public bool L_VIGENTE { get; set; }
        public string CID_TIPO { get; set; }
        public int NID_RUBRO_SUMA { get; set; }
        public string C_TITULAR { get; set; }
        public string V_CATALOGO { get; set; }
    }
}
