//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_RESTRICCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_RESTRICCIONES()
        {
            this.DECLARACION_RESTRICCIONES = new HashSet<DECLARACION_RESTRICCIONES>();
        }
    
        public int NID_RESTRICCION { get; set; }
        public string V_RESTRICCION { get; set; }
        public bool L_VIGENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_RESTRICCIONES> DECLARACION_RESTRICCIONES { get; set; }
    }
}
