//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ESTADO_TESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_ESTADO_TESTADO()
        {
            this.ALTA_ADEUDO = new HashSet<ALTA_ADEUDO>();
            this.ALTA_INMUEBLE = new HashSet<ALTA_INMUEBLE>();
            this.ALTA_INVERSION = new HashSet<ALTA_INVERSION>();
            this.ALTA_MUEBLE = new HashSet<ALTA_MUEBLE>();
            this.ALTA_VEHICULO = new HashSet<ALTA_VEHICULO>();
            this.DECLARACION_CARGO = new HashSet<DECLARACION_CARGO>();
            this.DECLARACION_DEPENDIENTES = new HashSet<DECLARACION_DEPENDIENTES>();
            this.DECLARACION_EXPERIENCIA_LABORAL = new HashSet<DECLARACION_EXPERIENCIA_LABORAL>();
            this.DECLARACION = new HashSet<DECLARACION>();
        }
    
        public int NID_ESTADO_TESTADO { get; set; }
        public string V_ESTADO_TESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_ADEUDO> ALTA_ADEUDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INMUEBLE> ALTA_INMUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_INVERSION> ALTA_INVERSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_MUEBLE> ALTA_MUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALTA_VEHICULO> ALTA_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_CARGO> DECLARACION_CARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_DEPENDIENTES> DECLARACION_DEPENDIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_EXPERIENCIA_LABORAL> DECLARACION_EXPERIENCIA_LABORAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION> DECLARACION { get; set; }
    }
}
