//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_REGIMEN_MATRIMONIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_REGIMEN_MATRIMONIAL()
        {
            this.DECLARACION_REGIMEN_MATRIMONIAL = new HashSet<DECLARACION_REGIMEN_MATRIMONIAL>();
        }
    
        public int NID_REGIMEN_MATRIMONIAL { get; set; }
        public string V_REGIMEN_MATRIMONIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_REGIMEN_MATRIMONIAL> DECLARACION_REGIMEN_MATRIMONIAL { get; set; }
    }
}
