//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFLICTO_RESPUESTA
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_CONFLICTO { get; set; }
        public int NID_RUBRO { get; set; }
        public int NID_ENCABEZADO { get; set; }
        public int NID_PREGUNTA { get; set; }
        public string V_RESPUESTA { get; set; }
    
        public virtual CAT_CONFLICTO_PREGUNTA CAT_CONFLICTO_PREGUNTA { get; set; }
        public virtual CONFLICTO_ENCABEZADO CONFLICTO_ENCABEZADO { get; set; }
    }
}
