//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_DOM_PARTICULAR
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public string C_CODIGO_POSTAL { get; set; }
        public int NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public string CID_MUNICIPIO { get; set; }
        public string V_COLONIA { get; set; }
        public string V_DOMICILIO { get; set; }
        public string V_CORREO { get; set; }
        public string V_TEL_PARTICULAR { get; set; }
        public string V_TEL_CELULAR { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
        public string V_ENTIDAD_FEDERATIVA { get; set; }
        public string V_MUNICIPIO { get; set; }
    
        public virtual DECLARACION DECLARACION { get; set; }
    }
}
