//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DECLARACION()
        {
            this.DECLARACION_APARTADO = new HashSet<DECLARACION_APARTADO>();
            this.DECLARACION_DEPENDIENTES = new HashSet<DECLARACION_DEPENDIENTES>();
            this.DECLARACION_EGRESOS = new HashSet<DECLARACION_EGRESOS>();
            this.DECLARACION_ESCOLARIDAD = new HashSet<DECLARACION_ESCOLARIDAD>();
            this.DECLARACION_EXPERIENCIA_LABORAL = new HashSet<DECLARACION_EXPERIENCIA_LABORAL>();
            this.DECLARACION_INGRESOS = new HashSet<DECLARACION_INGRESOS>();
            this.DECLARACION_REGIMEN_MATRIMONIAL = new HashSet<DECLARACION_REGIMEN_MATRIMONIAL>();
            this.DECLARACION_RESTRICCIONES = new HashSet<DECLARACION_RESTRICCIONES>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public string C_EJERCICIO { get; set; }
        public int NID_TIPO_DECLARACION { get; set; }
        public int NID_ESTADO { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
        public bool L_AUTORIZA_PUBLICAR { get; set; }
        public System.DateTime F_REGISTRO { get; set; }
        public Nullable<System.DateTime> F_ENVIO { get; set; }
        public Nullable<bool> L_CONFLICTO { get; set; }
        public string V_HASH { get; set; }
        public byte[] B_FILE_DECLARACION { get; set; }
    
        public virtual ALTA ALTA { get; set; }
        public virtual CAT_ESTADO_DECLARACION CAT_ESTADO_DECLARACION { get; set; }
        public virtual CAT_ESTADO_TESTADO CAT_ESTADO_TESTADO { get; set; }
        public virtual CAT_TIPO_DECLARACION CAT_TIPO_DECLARACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_APARTADO> DECLARACION_APARTADO { get; set; }
        public virtual DECLARACION_CARGO DECLARACION_CARGO { get; set; }
        public virtual DECLARACION_CARGO_OTRO DECLARACION_CARGO_OTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_DEPENDIENTES> DECLARACION_DEPENDIENTES { get; set; }
        public virtual DECLARACION_DOM_LABORAL DECLARACION_DOM_LABORAL { get; set; }
        public virtual DECLARACION_DOM_PARTICULAR DECLARACION_DOM_PARTICULAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_EGRESOS> DECLARACION_EGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_ESCOLARIDAD> DECLARACION_ESCOLARIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_EXPERIENCIA_LABORAL> DECLARACION_EXPERIENCIA_LABORAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_INGRESOS> DECLARACION_INGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_REGIMEN_MATRIMONIAL> DECLARACION_REGIMEN_MATRIMONIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION_RESTRICCIONES> DECLARACION_RESTRICCIONES { get; set; }
        public virtual MODIFICACION MODIFICACION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
