//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_DEPENDIENTES_PRIVADO
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_DEPENDIENTE { get; set; }
        public string V_NOMBRE { get; set; }
        public string V_CARGO { get; set; }
        public string V_RFC { get; set; }
        public System.DateTime F_INGRESO { get; set; }
        public int NID_SECTOR { get; set; }
        public decimal M_SALARIO_MENSUAL { get; set; }
        public bool L_PROVEEDOR { get; set; }
    
        public virtual CAT_SECTOR CAT_SECTOR { get; set; }
        public virtual DECLARACION_DEPENDIENTES DECLARACION_DEPENDIENTES { get; set; }
    }
}
