//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_DEPENDIENTES
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_DEPENDIENTE { get; set; }
        public int NID_TIPO_DEPENDIENTE { get; set; }
        public string E_NOMBRE { get; set; }
        public string E_PRIMER_A { get; set; }
        public string E_SEGUNDO_A { get; set; }
        public System.DateTime F_NACIMIENTO { get; set; }
        public string E_RFC { get; set; }
        public bool L_DEPENDE_ECO { get; set; }
        public string E_DOMICILIO { get; set; }
        public bool L_ACTIVO { get; set; }
        public bool L_CIUDADANO_EXTRANJERO { get; set; }
        public string E_CURP { get; set; }
        public int NID_ACTIVIDAD_LABORAL { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
        public bool L_MISMO_DOMICILIO_DECLARANTE { get; set; }
        public bool L_PAREJA { get; set; }
    
        public virtual CAT_ESTADO_TESTADO CAT_ESTADO_TESTADO { get; set; }
        public virtual CAT_TIPO_DEPENDIENTES CAT_TIPO_DEPENDIENTES { get; set; }
        public virtual DECLARACION DECLARACION { get; set; }
        public virtual DECLARACION_DEPENDIENTES_DOMICILIO DECLARACION_DEPENDIENTES_DOMICILIO { get; set; }
        public virtual DECLARACION_DEPENDIENTES_PRIVADO DECLARACION_DEPENDIENTES_PRIVADO { get; set; }
        public virtual DECLARACION_DEPENDIENTES_PUBLICO DECLARACION_DEPENDIENTES_PUBLICO { get; set; }
    }
}
