//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_PERSONALES
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public string C_GENERO { get; set; }
        public string C_CURP { get; set; }
        public int NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public int NID_NACIONALIDAD { get; set; }
        public int NID_ESTADO_CIVIL { get; set; }
        public Nullable<bool> L_SERVIDOR_ANTERIOR { get; set; }
        public Nullable<System.DateTime> F_SERVIDOR_ANTERIOR_INICIO { get; set; }
        public Nullable<System.DateTime> F_SERVIDOR_ANTERIOR_FIN { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
    }
}
