//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_REGIMEN_MATRIMONIAL
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_REGIMEN { get; set; }
        public int NID_REGIMEN_MATRIMONIAL { get; set; }
    
        public virtual CAT_REGIMEN_MATRIMONIAL CAT_REGIMEN_MATRIMONIAL { get; set; }
        public virtual DECLARACION DECLARACION { get; set; }
    }
}
