//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DECLARACION_ESCOLARIDAD
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_ESCOLARIDAD { get; set; }
        public int NID_NIVEL_ESCOLARIDAD { get; set; }
        public string V_INSTITUCION_EDUCATIVA { get; set; }
        public string V_CARRERA { get; set; }
        public int NID_ESTADO_ESCOLARIDAD { get; set; }
        public int NID_DOCUMENTO_OBTENIDO { get; set; }
        public System.DateTime F_OBTENCION { get; set; }
        public int NID_PAIS { get; set; }
        public string E_OBSERVACIONES { get; set; }
        public string E_OBSERVACIONES_MARCADO { get; set; }
        public string V_OBSERVACIONES_TESTADO { get; set; }
        public int NID_ESTADO_TESTADO { get; set; }
    
        public virtual CAT_DOCUMENTO_OBTENIDO CAT_DOCUMENTO_OBTENIDO { get; set; }
        public virtual CAT_ESTADO_ESCOLARIDAD CAT_ESTADO_ESCOLARIDAD { get; set; }
        public virtual CAT_NIVEL_ESCOLARIDAD CAT_NIVEL_ESCOLARIDAD { get; set; }
        public virtual CAT_PAIS CAT_PAIS { get; set; }
        public virtual DECLARACION DECLARACION { get; set; }
    }
}
