//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICACION_INVERSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODIFICACION_INVERSION()
        {
            this.MODIFICACION_INVERSION_TITU = new HashSet<MODIFICACION_INVERSION_TITU>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public decimal M_SALDO_ANTERIOR { get; set; }
        public decimal M_SALDO_ACTUAL { get; set; }
        public bool L_CANCELADA { get; set; }
        public bool L_MODIFICADA { get; set; }
    
        public virtual MODIFICACION MODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_INVERSION_TITU> MODIFICACION_INVERSION_TITU { get; set; }
    }
}
