//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICACION_ADEUDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODIFICACION_ADEUDO()
        {
            this.MODIFICACION_ADEUDO_TITULAR = new HashSet<MODIFICACION_ADEUDO_TITULAR>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public decimal M_PAGOS { get; set; }
        public decimal M_SALDOS { get; set; }
        public bool L_CANCELADO { get; set; }
        public bool L_MODIFICADO { get; set; }
    
        public virtual MODIFICACION MODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_ADEUDO_TITULAR> MODIFICACION_ADEUDO_TITULAR { get; set; }
    }
}
