//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICACION_TARJETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODIFICACION_TARJETA()
        {
            this.MODIFICACION_TARJETA_TITU = new HashSet<MODIFICACION_TARJETA_TITU>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public string E_NUMERO { get; set; }
        public int NID_INSTITUCION { get; set; }
        public string V_NUMERO_CORTO { get; set; }
        public decimal M_PAGOS { get; set; }
        public decimal M_SALDO { get; set; }
        public string E_NUMERO_ASOCIACION { get; set; }
        public bool L_ACTIVA { get; set; }
    
        public virtual CAT_INST_FINANCIERA CAT_INST_FINANCIERA { get; set; }
        public virtual MODIFICACION MODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_TARJETA_TITU> MODIFICACION_TARJETA_TITU { get; set; }
    }
}
