//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODIFICACION_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODIFICACION_VEHICULO()
        {
            this.MODIFICACION_VEHICULO_ADEU = new HashSet<MODIFICACION_VEHICULO_ADEU>();
            this.MODIFICACION_VEHICULO_TITU = new HashSet<MODIFICACION_VEHICULO_TITU>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_DECLARACION { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public int NID_MARCA { get; set; }
        public string C_MODELO { get; set; }
        public string V_DESCRIPCION { get; set; }
        public System.DateTime F_ADQUISICION { get; set; }
        public int NID_USO { get; set; }
        public decimal M_VALOR_VEHICULO { get; set; }
        public bool L_MODIFICADO { get; set; }
    
        public virtual CAT_MARCA_VEHICULO CAT_MARCA_VEHICULO { get; set; }
        public virtual CAT_USO_VEHICULO CAT_USO_VEHICULO { get; set; }
        public virtual MODIFICACION MODIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_VEHICULO_ADEU> MODIFICACION_VEHICULO_ADEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODIFICACION_VEHICULO_TITU> MODIFICACION_VEHICULO_TITU { get; set; }
    }
}
