//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATRIMONIO_MUEBLE
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public int NID_TIPO { get; set; }
        public string E_ESPECIFICACION { get; set; }
        public decimal M_VALOR { get; set; }
        public System.DateTime F_ADQUISICION { get; set; }
    
        public virtual CAT_TIPO_MUEBLE CAT_TIPO_MUEBLE { get; set; }
        public virtual PATRIMONIO PATRIMONIO { get; set; }
    }
}
