//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATRIMONIO_INVERSION
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public int NID_TIPO_INVERSION { get; set; }
        public int NID_SUBTIPO_INVERSION { get; set; }
        public int NID_INSTITUCION { get; set; }
        public string E_CUENTA { get; set; }
        public string V_CUENTA_CORTO { get; set; }
        public string V_OTRO { get; set; }
        public decimal M_SALDO { get; set; }
        public int NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public string V_LUGAR { get; set; }
    
        public virtual CAT_ENTIDAD_FEDERATIVA CAT_ENTIDAD_FEDERATIVA { get; set; }
        public virtual CAT_INST_FINANCIERA CAT_INST_FINANCIERA { get; set; }
        public virtual CAT_SUBTIPO_INVERSION CAT_SUBTIPO_INVERSION { get; set; }
        public virtual PATRIMONIO PATRIMONIO { get; set; }
    }
}
