//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATRIMONIO_TARJETA
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_PATRIMONIO { get; set; }
        public int NID_INSTITUCION { get; set; }
        public decimal M_SALDO { get; set; }
        public Nullable<long> NID_PAIS { get; set; }
        public string CID_ENTIDAD_FEDERATIVA { get; set; }
        public Nullable<long> NID_TIPO_ADEUDO { get; set; }
        public string V_LUGAR { get; set; }
        public string V_OTRA { get; set; }
        public Nullable<decimal> M_ORIGINAL { get; set; }
        public string E_CUENTA { get; set; }
    
        public virtual PATRIMONIO PATRIMONIO { get; set; }
    }
}
