//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.DECLARACION = new HashSet<DECLARACION>();
            this.PATRIMONIO = new HashSet<PATRIMONIO>();
            this.USUARIO_CORREO = new HashSet<USUARIO_CORREO>();
            this.USUARIO_DOMICILIO = new HashSet<USUARIO_DOMICILIO>();
            this.USUARIO_REC_PASS = new HashSet<USUARIO_REC_PASS>();
            this.USUARIO_SESION = new HashSet<USUARIO_SESION>();
        }
    
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public string V_PASSWORD { get; set; }
        public string V_NOMBRE { get; set; }
        public string V_PRIMER_A { get; set; }
        public string V_SEGUNDO_A { get; set; }
        public System.DateTime F_NACIMIENTO { get; set; }
        public string V_ACUSE { get; set; }
        public bool L_ACTIVO { get; set; }
        public System.DateTime F_INGRESO_INSTITUTO { get; set; }
        public System.DateTime F_REGISTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECLARACION> DECLARACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATRIMONIO> PATRIMONIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_CORREO> USUARIO_CORREO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_DOMICILIO> USUARIO_DOMICILIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_REC_PASS> USUARIO_REC_PASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_SESION> USUARIO_SESION { get; set; }
        public bool NVO_INGRESO { get; set; }
        public bool OBL_DECLARACION { get; set; }
    }
}
