//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_SESION
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public int NID_SESION { get; set; }
        public string V_IP { get; set; }
        public string V_MAQUINA_USUARIO { get; set; }
        public System.DateTime F_INICIO { get; set; }
        public System.DateTime F_FIN { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
