//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELDeclara_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_CORREO
    {
        public string VID_NOMBRE { get; set; }
        public string VID_FECHA { get; set; }
        public string VID_HOMOCLAVE { get; set; }
        public string V_CORREO { get; set; }
        public bool L_PRINCIPAL { get; set; }
        public bool L_ACTIVO { get; set; }
        public bool L_CONFIRMADO { get; set; }
        public int N_CODIGO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
