//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TIPO_ACTIVIDAD
    {
        public decimal ID_TIPO_ACTIVIDAD { get; set; }
        public string DESC_TIPO_ACTIVIDAD { get; set; }
    }
}
