//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_DESTINORECURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_DESTINORECURSOS()
        {
            this.D_VENTAINVERSIONES = new HashSet<D_VENTAINVERSIONES>();
            this.D_VENTAINMUEBLE = new HashSet<D_VENTAINMUEBLE>();
        }
    
        public decimal TIPO_DESTINORECURSOS { get; set; }
        public string DESC_TIPORECURSOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VENTAINVERSIONES> D_VENTAINVERSIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VENTAINMUEBLE> D_VENTAINMUEBLE { get; set; }
    }
}
