//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_FORMADQUI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_FORMADQUI()
        {
            this.D_VEHICULO = new HashSet<D_VEHICULO>();
            this.D_INMUEBLES = new HashSet<D_INMUEBLES>();
            this.D_MUEBLES = new HashSet<D_MUEBLES>();
            this.D_VENTAINMUEBLE = new HashSet<D_VENTAINMUEBLE>();
            this.D_VENTAVEHICULO = new HashSet<D_VENTAVEHICULO>();
            this.D_VENTAMUEBLE = new HashSet<D_VENTAMUEBLE>();
        }
    
        public decimal TIPO_FORMA { get; set; }
        public string DESC_TIPOFORMA { get; set; }
        public string NOTA { get; set; }
        public string NOTA_VENTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VEHICULO> D_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_INMUEBLES> D_INMUEBLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_MUEBLES> D_MUEBLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VENTAINMUEBLE> D_VENTAINMUEBLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VENTAVEHICULO> D_VENTAVEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VENTAMUEBLE> D_VENTAMUEBLE { get; set; }
    }
}
