//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_ESTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_ESTADOS()
        {
            this.D_INVERSIONES = new HashSet<D_INVERSIONES>();
            this.CAT_MUNICIPIO = new HashSet<CAT_MUNICIPIO>();
            this.D_DETDOMICILIOPERSONAL = new HashSet<D_DETDOMICILIOPERSONAL>();
            this.D_DETDOMICILIOLABORAL = new HashSet<D_DETDOMICILIOLABORAL>();
            this.D_DATOSPERSONALES = new HashSet<D_DATOSPERSONALES>();
        }
    
        public decimal ID_ESTADO { get; set; }
        public string DESC_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_INVERSIONES> D_INVERSIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_MUNICIPIO> CAT_MUNICIPIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DETDOMICILIOPERSONAL> D_DETDOMICILIOPERSONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DETDOMICILIOLABORAL> D_DETDOMICILIOLABORAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DATOSPERSONALES> D_DATOSPERSONALES { get; set; }
    }
}
