//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_COMPARA_PTO
    {
        public Nullable<short> ANIO { get; set; }
        public Nullable<short> NUM_PTO { get; set; }
        public string TABULADOR { get; set; }
        public string NIVEL { get; set; }
        public string DESC_PTO { get; set; }
        public string REGIMEN { get; set; }
    }
}
