//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PTO_2015
    {
        public string TABULADOR { get; set; }
        public string NIVEL { get; set; }
        public string DESC_PTO { get; set; }
        public string NIVEL_ANTERIOR { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<decimal> DEDUC { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public string REGIMEN { get; set; }
    }
}
