//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFLICTO
    {
        public decimal NUM_EMPLEADO { get; set; }
        public short ANIO { get; set; }
        public string PUBLICA_DATO { get; set; }
        public System.DateTime FCAPTURA { get; set; }
        public string DEC_PUB_NING { get; set; }
        public string DEC_PRIV_NING { get; set; }
        public string DEC_OBSERVA { get; set; }
        public string DEC_OBS_NINGUNA { get; set; }
        public string EXISTE_CONF { get; set; }
        public string CERRAR { get; set; }
        public string RELACION { get; set; }
        public short IDCONFLICTO { get; set; }
    }
}
