//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA_REVISADOS
    {
        public short ANIO { get; set; }
        public string CURP { get; set; }
        public string NOMBRE { get; set; }
        public string PUESTO { get; set; }
        public string ADSCRIPCION { get; set; }
        public Nullable<long> INGRESO { get; set; }
        public Nullable<long> EGRESO { get; set; }
        public Nullable<int> DIFERENCIA { get; set; }
        public Nullable<decimal> POR_DIF { get; set; }
        public Nullable<System.DateTime> FCONSULTA { get; set; }
    }
}
