//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ACTIVIDAD_ACADEMICA
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public decimal ID_ACTIVIDAD_ACADEMICA { get; set; }
        public Nullable<decimal> ID_TIPO { get; set; }
        public Nullable<decimal> ID_NIVEL { get; set; }
        public string OTRO_NIVEL { get; set; }
        public string INSTITUCION { get; set; }
        public string MATERIA_CURSO { get; set; }
        public Nullable<System.DateTime> INI_PERIODO { get; set; }
        public Nullable<System.DateTime> FIN_PERIODO { get; set; }
        public string OTRO_TIPO { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA_ACTIVIDAD { get; set; }
    }
}
