//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ADEUDOS
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public decimal ID_ADEUDO { get; set; }
        public Nullable<decimal> TIPO_ADEUDO { get; set; }
        public string OTRO_TIPOADEUDO { get; set; }
        public Nullable<decimal> ID_INSTITUTO { get; set; }
        public string OTRO_INSTITUTO { get; set; }
        public string NUM_CUENTA { get; set; }
        public Nullable<decimal> ID_PAIS { get; set; }
        public string OTRO_PAIS { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public Nullable<decimal> TIPO_DESTINORECURSOS { get; set; }
        public string OTRO_DESTINORECURSOS { get; set; }
        public Nullable<System.DateTime> FEC_OTORGAMIENTO { get; set; }
        public Nullable<decimal> ADEUDO_ORIGINAL { get; set; }
        public Nullable<decimal> SALDO_INSOLUTO { get; set; }
        public Nullable<decimal> MONTO_PAGOS { get; set; }
        public Nullable<decimal> TITULAR { get; set; }
        public string OTRO_TITULAR { get; set; }
        public string STATUS_ADEUDO { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA { get; set; }
        public string TERMINADO { get; set; }
        public string PRECARGADO { get; set; }
    
        public virtual D_DECLARA D_DECLARA { get; set; }
    }
}
