//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ART8
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public Nullable<System.DateTime> FEC_SOCIEDAD { get; set; }
        public Nullable<decimal> ID_CONTRATACIONES { get; set; }
        public string NOMBRE { get; set; }
        public string ACTIVIDAD { get; set; }
        public string PARTICIPACION { get; set; }
        public string PORCENTAJE { get; set; }
        public Nullable<decimal> ID_INHABILITADO { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA { get; set; }
    }
}
