//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_DATOSPERSONALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_DATOSPERSONALES()
        {
            this.D_DECLARA = new HashSet<D_DECLARA>();
            this.D_DETDOMICILIOPERSONAL = new HashSet<D_DETDOMICILIOPERSONAL>();
            this.D_DETDOMICILIOLABORAL = new HashSet<D_DETDOMICILIOLABORAL>();
        }
    
        public decimal NUM_EMPLEADO { get; set; }
        public string CURP { get; set; }
        public decimal ID_FOLIO { get; set; }
        public string RFC { get; set; }
        public string HOMO { get; set; }
        public string A_PAT { get; set; }
        public string A_MAT { get; set; }
        public string NOMBRE { get; set; }
        public string GENERO { get; set; }
        public Nullable<decimal> EDO_CIVIL { get; set; }
        public Nullable<decimal> ID_PAIS { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public Nullable<decimal> ID_MUNICIPIO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string OTRO_PAIS { get; set; }
        public string OTRO_LUGAR { get; set; }
    
        public virtual CAT_EDOCIVIL CAT_EDOCIVIL { get; set; }
        public virtual CAT_ESTADOS CAT_ESTADOS { get; set; }
        public virtual CAT_MUNICIPIO CAT_MUNICIPIO { get; set; }
        public virtual CAT_PAIS CAT_PAIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DECLARA> D_DECLARA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DETDOMICILIOPERSONAL> D_DETDOMICILIOPERSONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_DETDOMICILIOLABORAL> D_DETDOMICILIOLABORAL { get; set; }
    }
}
