//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_DECLARA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public D_DECLARA()
        {
            this.D_ADEUDOS = new HashSet<D_ADEUDOS>();
            this.D_INMUEBLES = new HashSet<D_INMUEBLES>();
            this.D_VEHICULO = new HashSet<D_VEHICULO>();
            this.D_MUEBLES = new HashSet<D_MUEBLES>();
            this.D_INVERSIONES = new HashSet<D_INVERSIONES>();
        }
    
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public Nullable<System.DateTime> FEC_INI_FIN_PTO { get; set; }
        public Nullable<System.DateTime> FEC_INGRESO_IFE { get; set; }
        public string CVE_UADMON { get; set; }
        public Nullable<decimal> CVE_AREA { get; set; }
        public string TABULADOR { get; set; }
        public string NIVEL { get; set; }
        public string SP { get; set; }
        public string ART { get; set; }
        public Nullable<decimal> ID_DOMICILIOP { get; set; }
        public Nullable<decimal> ID_DOMICILIOLAB { get; set; }
        public string PARTICIPA_MHF { get; set; }
        public Nullable<decimal> GASTOS_MANUTENCION { get; set; }
        public string AUTORIZA_PUBLICAR { get; set; }
        public string LUGAR_ELABORA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA { get; set; }
        public string ADJUDICACION { get; set; }
        public string HORA_CAPTURA { get; set; }
        public string DENOMINA_CARGO { get; set; }
    
        public virtual CAT_TIPO_DECLARA CAT_TIPO_DECLARA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_ADEUDOS> D_ADEUDOS { get; set; }
        public virtual D_DATOSPERSONALES D_DATOSPERSONALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_INMUEBLES> D_INMUEBLES { get; set; }
        public virtual D_MONTOENCARGO D_MONTOENCARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_VEHICULO> D_VEHICULO { get; set; }
        public virtual DETDECLARADEPENDIENTES DETDECLARADEPENDIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_MUEBLES> D_MUEBLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D_INVERSIONES> D_INVERSIONES { get; set; }
        public virtual D_DETDOMICILIOLABORAL D_DETDOMICILIOLABORAL { get; set; }
        public virtual D_DETDOMICILIOPERSONAL D_DETDOMICILIOPERSONAL { get; set; }
    }
}
