//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_ESCOLARIDAD
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public Nullable<decimal> ID_GRADO_ESTUDIO { get; set; }
        public string OTRO_GRADO_ESTUDIO { get; set; }
        public Nullable<decimal> ID_PAIS { get; set; }
        public string OTRO_PAIS { get; set; }
        public Nullable<decimal> ID_ESTADO { get; set; }
        public string OTRO_ESTADO { get; set; }
        public string INSTITUCION { get; set; }
        public string CARRERA { get; set; }
        public Nullable<decimal> ID_ESTATUS { get; set; }
        public Nullable<decimal> ID_PERIODO { get; set; }
        public string OTRO_PERIODO { get; set; }
        public Nullable<decimal> COMPLETOS { get; set; }
        public Nullable<decimal> TOTALES { get; set; }
        public Nullable<decimal> ID_OTROS_ESTUDIOS { get; set; }
        public string OTROS_ESTUDIOS { get; set; }
        public string CED_PROFESIONAL { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA { get; set; }
    }
}
