//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_MONTOENCARGO
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public Nullable<System.DateTime> FEC_PER_INI { get; set; }
        public Nullable<System.DateTime> FEC_PER_FIN { get; set; }
        public Nullable<decimal> MONTO_ENCARGO { get; set; }
        public string DESC_OTRO_INGRESO { get; set; }
        public Nullable<decimal> MONTO_OTRO_INGRESO { get; set; }
        public Nullable<decimal> SUMAI_II { get; set; }
        public Nullable<decimal> MONTO_CONYU_DEPENDE { get; set; }
        public Nullable<decimal> SUMAA_B { get; set; }
        public string PRESENTA_DECLAR_IMPUSTOS { get; set; }
        public Nullable<System.DateTime> FEC_CAPTURA { get; set; }
        public string DESC_CONYU_DEPENDE { get; set; }
    
        public virtual D_DECLARA D_DECLARA { get; set; }
    }
}
