//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_PUBLICO
    {
        public decimal NUM_EMPLEADO { get; set; }
        public short ANIO { get; set; }
        public byte IDENTIDAD { get; set; }
        public string NOMBRE { get; set; }
        public string UBICACION { get; set; }
        public Nullable<short> ENTIDAD { get; set; }
        public string PAIS { get; set; }
        public Nullable<int> NAT_VINC { get; set; }
        public string OTRA_NATVINC { get; set; }
        public Nullable<byte> ANT_VINC_ANIOS { get; set; }
        public Nullable<byte> FRECUENCIA { get; set; }
        public string OTRA_FRECUENCIA { get; set; }
        public Nullable<bool> PARTICIPACION { get; set; }
        public Nullable<bool> CUANDO { get; set; }
        public Nullable<byte> PER_JURIDICA { get; set; }
        public string OTRA_PER_JUR { get; set; }
        public Nullable<byte> APORTE { get; set; }
        public string OTRO_APORTE { get; set; }
        public bool TITULAR { get; set; }
        public string RFC { get; set; }
        public System.DateTime FCAPTURA { get; set; }
        public short IDCONFLICTO { get; set; }
    }
}
