//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PADRON_2014_P
    {
        public int ID { get; set; }
        public Nullable<long> NUM_EMPLEADO { get; set; }
        public string RFC { get; set; }
        public string NOMBRE { get; set; }
        public string CURP { get; set; }
        public string SEXO { get; set; }
        public string REGIMEN { get; set; }
        public string PUESTO_TRAB { get; set; }
        public string RADICACION { get; set; }
        public string TABULADOR { get; set; }
        public string INGRESO { get; set; }
        public string PLAZA { get; set; }
        public string UNIDAD_RESP { get; set; }
        public string AREA_ORGAN { get; set; }
    }
}
