//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPORAL_EVOL_PAT
    {
        public int ID { get; set; }
        public int NUM_EMPLEADO { get; set; }
        public short ANIO { get; set; }
        public byte ORDEN { get; set; }
        public Nullable<long> DECLA { get; set; }
        public Nullable<long> CONYUGE { get; set; }
        public Nullable<long> CONC { get; set; }
        public Nullable<long> DEPEND { get; set; }
        public Nullable<long> DECLA_CONY { get; set; }
        public Nullable<long> DELCA_CONC { get; set; }
        public Nullable<long> DECLA_DEPEND { get; set; }
        public Nullable<long> DECLA_COPROP { get; set; }
        public Nullable<long> CONY_DEPEND { get; set; }
        public Nullable<long> CONY_COPROP { get; set; }
        public Nullable<long> CONC_DEPEND { get; set; }
        public Nullable<long> CONC_COPROP { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    }
}
