//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_ESTADISTICAS
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal IDCONSULTA { get; set; }
        public decimal NUMERO { get; set; }
        public Nullable<System.DateTime> FEC_INI_FIN_PTO { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public string REGIMEN { get; set; }
        public string DESC_UADMON { get; set; }
        public string DESC_AREA { get; set; }
        public string DESC_PTO { get; set; }
        public Nullable<System.DateTime> FEC_ENVIO { get; set; }
        public string PUBLICA { get; set; }
        public Nullable<short> EJERCICIO { get; set; }
    }
}
