//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARTIFICIO_INV_VEHIC
    {
        public decimal NUM_EMPLEADO { get; set; }
        public string TIPO_BIEN { get; set; }
        public Nullable<decimal> ID_MARCA { get; set; }
        public string MODELO_VEHICULO { get; set; }
        public Nullable<decimal> ANIO_VEHICULO { get; set; }
        public string CARACT { get; set; }
        public Nullable<System.DateTime> FEC_ADQUI { get; set; }
        public Nullable<decimal> VALOR_ADQUI { get; set; }
        public Nullable<decimal> TIPO_USO { get; set; }
        public string DESC_USO { get; set; }
        public Nullable<decimal> TIPO_FORMA { get; set; }
        public Nullable<decimal> TITULAR { get; set; }
        public string DESC_TIPOFORMA { get; set; }
        public string OTRO_TITULAR { get; set; }
        public string NOMBRE_DONANTE { get; set; }
    }
}
