//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCAT_ESTADOS_DOMICILIO
    {
        public decimal ID_ESTADO { get; set; }
        public string DESC_ESTADO { get; set; }
    }
}
