//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCOM_2014_2015
    {
        public decimal ANIO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public System.DateTime FEC_ENVIO { get; set; }
    }
}
