//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCONTROL_AREA
    {
        public string CVE_UADMON { get; set; }
        public decimal CVE_AREA { get; set; }
        public string DESC_AREA { get; set; }
        public string STATUS { get; set; }
        public decimal ANIO { get; set; }
    }
}
