//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDATOS_DECLARANTE_SITUACION
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public string NOMBRE { get; set; }
        public string DESC_PTO { get; set; }
        public string DESC_UADMON { get; set; }
        public System.DateTime FEC_ENVIO { get; set; }
    }
}
