//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDOMICILIOS_DEPENDIENTES
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public Nullable<decimal> ID_DEPENDIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string EDAD { get; set; }
        public string SEXO { get; set; }
        public string DESC_PARENTESCO { get; set; }
        public string MISMO_DOMICILIO { get; set; }
        public Nullable<decimal> ID_DOMICILIODEP { get; set; }
    }
}
