//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENV_TRANSPARENCIA
    {
        public Nullable<short> EJERCICIO { get; set; }
        public string OBLIGADO { get; set; }
        public string NIVEL { get; set; }
        public string DESC_PTO { get; set; }
        public string CARGO { get; set; }
        public string DESC_AREA { get; set; }
        public string NOMBRE { get; set; }
        public string A_PAT { get; set; }
        public string A_MAT { get; set; }
        public string MODALIDAD { get; set; }
        public string HIPERVINCULO { get; set; }
        public string FVALIDA { get; set; }
        public string RESPONSABLE { get; set; }
        public string ANIO { get; set; }
        public string FACTUALIZACION { get; set; }
    }
}
