//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEXP_PUBLICA
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public string GOBIERNO { get; set; }
        public string AMBITO { get; set; }
        public string INSTITUCION { get; set; }
        public string UNIDAD_ADMIN { get; set; }
        public string PUESTO { get; set; }
        public string ACTIVIDAD_PRINCIPAL { get; set; }
        public string INICIO { get; set; }
        public string TERMINO { get; set; }
    }
}
