//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHIST_ADEUDO
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public string TIPOADEUDO { get; set; }
        public string CARACT { get; set; }
        public Nullable<decimal> MONTO_PAGOS { get; set; }
        public Nullable<decimal> SALDO_INSOLUTO { get; set; }
        public Nullable<decimal> TITULAR { get; set; }
        public string NUM_CUENTA { get; set; }
        public Nullable<decimal> TIPO_ADEUDO { get; set; }
    }
}
