//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VINVERSIONES
    {
        public Nullable<decimal> NUM_EMPLEADO { get; set; }
        public Nullable<decimal> ID_DECLARA { get; set; }
        public Nullable<decimal> T_D { get; set; }
        public Nullable<decimal> ANIO { get; set; }
        public string DESC_INVERSION { get; set; }
        public string NUM_CUENTA { get; set; }
        public string DESC_INSTITUTO { get; set; }
        public string LOCALIZA { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public string DESC_TITULAR { get; set; }
        public Nullable<decimal> ID_INVERSION { get; set; }
        public string DESC_STATUSINVERSION { get; set; }
        public decimal TITULAR { get; set; }
        public Nullable<decimal> TIPO_INVERSION { get; set; }
    }
}
