//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMONITOR_CONFLICTO
    {
        public decimal NUM_EMPLEADO { get; set; }
        public short ANIO { get; set; }
        public System.DateTime FCAPTURA { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string NOMBRE { get; set; }
        public string CERRAR { get; set; }
        public short IDCONFLICTO { get; set; }
        public string SOPA { get; set; }
    }
}
