//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTRO_INGRESO
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public Nullable<decimal> ORDEN { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<decimal> PAGOS { get; set; }
        public Nullable<decimal> TITULAR { get; set; }
        public Nullable<decimal> ID { get; set; }
    }
}
