//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPINTA_GRAFICA
    {
        public string ORDEN { get; set; }
        public System.DateTime FEC_ENVIO { get; set; }
        public decimal T_D { get; set; }
        public Nullable<System.DateTime> FEC_INI_FIN_PTO { get; set; }
        public string AUTORIZA { get; set; }
        public string NOMBRE { get; set; }
        public string RFC { get; set; }
        public Nullable<decimal> EJERCICIO { get; set; }
        public string DESC_PTO { get; set; }
        public string REGIMEN { get; set; }
        public string CVE_UADMON { get; set; }
        public string DESC_UADMON { get; set; }
        public string DESC_AREA { get; set; }
    }
}
