//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VREPSINDECLA
    {
        public string RFC { get; set; }
        public Nullable<System.DateTime> FEC_DECLARACION { get; set; }
        public Nullable<decimal> ANIO_DECLARACION { get; set; }
        public string DECLARA_ANTERIOR { get; set; }
    }
}
