//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSIN_INICIAL_2015
    {
        public Nullable<int> FOLIO { get; set; }
        public string RFC { get; set; }
        public string NOMBRE { get; set; }
        public string CURP { get; set; }
        public string SEXO { get; set; }
        public string REGIMEN { get; set; }
        public string PUESTO { get; set; }
        public string RADICACION { get; set; }
        public string NIVEL { get; set; }
        public string INGRESO { get; set; }
        public string NPUESTO { get; set; }
        public string UNIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> PERCEPCION { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public Nullable<decimal> BRUTO { get; set; }
        public string ANIO { get; set; }
    }
}
