//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUTILESCANEO_2010
    {
        public decimal NUM_EMPLEADO { get; set; }
        public string CURP { get; set; }
        public string A_PAT { get; set; }
        public string A_MAT { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_DECLARACION { get; set; }
        public Nullable<decimal> T_D { get; set; }
        public Nullable<decimal> ANIO { get; set; }
        public Nullable<System.DateTime> FEC_ENVIO { get; set; }
        public string FIRMA { get; set; }
        public string AUTORIZA_PUBLICAR { get; set; }
        public string RFC { get; set; }
        public string SOPA { get; set; }
    }
}
