//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVEHICULOS
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARA { get; set; }
        public decimal T_D { get; set; }
        public decimal ANIO { get; set; }
        public string AUTOS { get; set; }
        public string DESC_TIPOFORMA { get; set; }
        public Nullable<System.DateTime> FEC_ADQUI { get; set; }
        public Nullable<decimal> VALOR_ADQUI { get; set; }
        public string DESC_USO { get; set; }
        public string DESC_TITULAR { get; set; }
        public Nullable<decimal> SALDO_INSOLUTO { get; set; }
        public Nullable<decimal> MONTO_PAGOS { get; set; }
        public string NOMBRE_DONANTE { get; set; }
        public decimal ID_VEHICULO { get; set; }
        public string VENDIDO { get; set; }
    }
}
