//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVENTAINVERSION
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARAV { get; set; }
        public decimal T_DV { get; set; }
        public decimal ANIOV { get; set; }
        public string NOMINVERSION { get; set; }
        public string NUM_CUENTA { get; set; }
        public string INSTITUTO { get; set; }
        public string PAIS { get; set; }
        public string DESC_ESTADO { get; set; }
        public string FORMAVENTA { get; set; }
        public Nullable<System.DateTime> FEC_VENTA { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public string DESTINO_RECURSOS { get; set; }
        public string DESC_TITULAR { get; set; }
        public decimal ID_INVERSIONV { get; set; }
    }
}
