//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVENTAVEHICULOS_TITULAR
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARAV { get; set; }
        public decimal T_DV { get; set; }
        public decimal ANIOV { get; set; }
        public Nullable<decimal> CUENTA { get; set; }
    }
}
