//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVENTAINMUEBLES
    {
        public decimal NUM_EMPLEADO { get; set; }
        public decimal ID_DECLARAV { get; set; }
        public decimal T_DV { get; set; }
        public decimal ANIOV { get; set; }
        public string TIPOINMUEBLE { get; set; }
        public string UBICACION { get; set; }
        public Nullable<decimal> METRO_TERRENO { get; set; }
        public Nullable<decimal> METRO_CONSTRUC { get; set; }
        public string DESC_TIPOFORMA { get; set; }
        public Nullable<System.DateTime> FECHA_VENTA { get; set; }
        public Nullable<decimal> VALOR_VENTA { get; set; }
        public string DESTINO_RECURSOS { get; set; }
        public string DESC_TITULAR { get; set; }
        public Nullable<decimal> SALDO_INSOLUTOV { get; set; }
        public Nullable<decimal> MONTO_PAGOSV { get; set; }
        public string NOMBRE_DONANTE { get; set; }
    }
}
