//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclaraINAI.Legacy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeclara", Namespace="http://inai.mx/")]
    [System.SerializableAttribute()]
    public partial class ListaDeclara : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Num_EmpleadoField;
        
        private int ID_DeclaraField;
        
        private int T_DField;
        
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hora_EnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fec_EnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_T_DField;
        
        private int ClasificaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Num_Empleado {
            get {
                return this.Num_EmpleadoField;
            }
            set {
                if ((this.Num_EmpleadoField.Equals(value) != true)) {
                    this.Num_EmpleadoField = value;
                    this.RaisePropertyChanged("Num_Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_Declara {
            get {
                return this.ID_DeclaraField;
            }
            set {
                if ((this.ID_DeclaraField.Equals(value) != true)) {
                    this.ID_DeclaraField = value;
                    this.RaisePropertyChanged("ID_Declara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int T_D {
            get {
                return this.T_DField;
            }
            set {
                if ((this.T_DField.Equals(value) != true)) {
                    this.T_DField = value;
                    this.RaisePropertyChanged("T_D");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Hora_Envio {
            get {
                return this.Hora_EnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.Hora_EnvioField, value) != true)) {
                    this.Hora_EnvioField = value;
                    this.RaisePropertyChanged("Hora_Envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Fec_Envio {
            get {
                return this.Fec_EnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fec_EnvioField, value) != true)) {
                    this.Fec_EnvioField = value;
                    this.RaisePropertyChanged("Fec_Envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Desc_T_D {
            get {
                return this.Desc_T_DField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_T_DField, value) != true)) {
                    this.Desc_T_DField = value;
                    this.RaisePropertyChanged("Desc_T_D");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Clasifica {
            get {
                return this.ClasificaField;
            }
            set {
                if ((this.ClasificaField.Equals(value) != true)) {
                    this.ClasificaField = value;
                    this.RaisePropertyChanged("Clasifica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaAnt2010", Namespace="http://inai.mx/")]
    [System.SerializableAttribute()]
    public partial class ListaAnt2010 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_DECLARACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIP_DECLARACIONField;
        
        private int ANIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DECLARACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACUSEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_DECLARACION {
            get {
                return this.ID_DECLARACIONField;
            }
            set {
                if ((this.ID_DECLARACIONField.Equals(value) != true)) {
                    this.ID_DECLARACIONField = value;
                    this.RaisePropertyChanged("ID_DECLARACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TIP_DECLARACION {
            get {
                return this.TIP_DECLARACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIP_DECLARACIONField, value) != true)) {
                    this.TIP_DECLARACIONField = value;
                    this.RaisePropertyChanged("TIP_DECLARACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ANIO {
            get {
                return this.ANIOField;
            }
            set {
                if ((this.ANIOField.Equals(value) != true)) {
                    this.ANIOField = value;
                    this.RaisePropertyChanged("ANIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DECLARACION {
            get {
                return this.DECLARACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DECLARACIONField, value) != true)) {
                    this.DECLARACIONField = value;
                    this.RaisePropertyChanged("DECLARACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ACUSE {
            get {
                return this.ACUSEField;
            }
            set {
                if ((object.ReferenceEquals(this.ACUSEField, value) != true)) {
                    this.ACUSEField = value;
                    this.RaisePropertyChanged("ACUSE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inai.mx/", ConfigurationName="Legacy.fileSoap")]
    public interface fileSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NOMARCH del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Transparencia", ReplyAction="*")]
        DeclaraINAI.Legacy.TransparenciaResponse Transparencia(DeclaraINAI.Legacy.TransparenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Transparencia", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.TransparenciaResponse> TransparenciaAsync(DeclaraINAI.Legacy.TransparenciaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NOMARCH del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Modificacion", ReplyAction="*")]
        DeclaraINAI.Legacy.ModificacionResponse Modificacion(DeclaraINAI.Legacy.ModificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Modificacion", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ModificacionResponse> ModificacionAsync(DeclaraINAI.Legacy.ModificacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NOMARCH del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Inicial", ReplyAction="*")]
        DeclaraINAI.Legacy.InicialResponse Inicial(DeclaraINAI.Legacy.InicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Inicial", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.InicialResponse> InicialAsync(DeclaraINAI.Legacy.InicialRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NOMARCH del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Conclusion", ReplyAction="*")]
        DeclaraINAI.Legacy.ConclusionResponse Conclusion(DeclaraINAI.Legacy.ConclusionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Conclusion", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConclusionResponse> ConclusionAsync(DeclaraINAI.Legacy.ConclusionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NOMARCH del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Acuse", ReplyAction="*")]
        DeclaraINAI.Legacy.AcuseResponse Acuse(DeclaraINAI.Legacy.AcuseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Acuse", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.AcuseResponse> AcuseAsync(DeclaraINAI.Legacy.AcuseRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ResponsivaResult del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Responsiva", ReplyAction="*")]
        DeclaraINAI.Legacy.ResponsivaResponse Responsiva(DeclaraINAI.Legacy.ResponsivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Responsiva", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ResponsivaResponse> ResponsivaAsync(DeclaraINAI.Legacy.ResponsivaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento EstadisticaResult del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Estadistica", ReplyAction="*")]
        DeclaraINAI.Legacy.EstadisticaResponse Estadistica(DeclaraINAI.Legacy.EstadisticaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Estadistica", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.EstadisticaResponse> EstadisticaAsync(DeclaraINAI.Legacy.EstadisticaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Dia del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Conflicto", ReplyAction="*")]
        DeclaraINAI.Legacy.ConflictoResponse Conflicto(DeclaraINAI.Legacy.ConflictoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Conflicto", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConflictoResponse> ConflictoAsync(DeclaraINAI.Legacy.ConflictoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RFC del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Consulta", ReplyAction="*")]
        DeclaraINAI.Legacy.ConsultaResponse Consulta(DeclaraINAI.Legacy.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConsultaResponse> ConsultaAsync(DeclaraINAI.Legacy.ConsultaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RFC del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Consulta2010", ReplyAction="*")]
        DeclaraINAI.Legacy.Consulta2010Response Consulta2010(DeclaraINAI.Legacy.Consulta2010Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/Consulta2010", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.Consulta2010Response> Consulta2010Async(DeclaraINAI.Legacy.Consulta2010Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Archivo del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/AcuseAnt2010", ReplyAction="*")]
        DeclaraINAI.Legacy.AcuseAnt2010Response AcuseAnt2010(DeclaraINAI.Legacy.AcuseAnt2010Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/AcuseAnt2010", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.AcuseAnt2010Response> AcuseAnt2010Async(DeclaraINAI.Legacy.AcuseAnt2010Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Archivo del espacio de nombres http://inai.mx/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/DeclaraAnt2010", ReplyAction="*")]
        DeclaraINAI.Legacy.DeclaraAnt2010Response DeclaraAnt2010(DeclaraINAI.Legacy.DeclaraAnt2010Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inai.mx/DeclaraAnt2010", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.DeclaraAnt2010Response> DeclaraAnt2010Async(DeclaraINAI.Legacy.DeclaraAnt2010Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransparenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Transparencia", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.TransparenciaRequestBody Body;
        
        public TransparenciaRequest() {
        }
        
        public TransparenciaRequest(DeclaraINAI.Legacy.TransparenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class TransparenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ENVIADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FIMPRESION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FEC_ENVIO;
        
        public TransparenciaRequestBody() {
        }
        
        public TransparenciaRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH, string ENVIADO, string FIMPRESION, string FEC_ENVIO) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
            this.ENVIADO = ENVIADO;
            this.FIMPRESION = FIMPRESION;
            this.FEC_ENVIO = FEC_ENVIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransparenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransparenciaResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.TransparenciaResponseBody Body;
        
        public TransparenciaResponse() {
        }
        
        public TransparenciaResponse(DeclaraINAI.Legacy.TransparenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class TransparenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TransparenciaResult;
        
        public TransparenciaResponseBody() {
        }
        
        public TransparenciaResponseBody(byte[] TransparenciaResult) {
            this.TransparenciaResult = TransparenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificacion", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ModificacionRequestBody Body;
        
        public ModificacionRequest() {
        }
        
        public ModificacionRequest(DeclaraINAI.Legacy.ModificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ModificacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public ModificacionRequestBody() {
        }
        
        public ModificacionRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificacionResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ModificacionResponseBody Body;
        
        public ModificacionResponse() {
        }
        
        public ModificacionResponse(DeclaraINAI.Legacy.ModificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ModificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ModificacionResult;
        
        public ModificacionResponseBody() {
        }
        
        public ModificacionResponseBody(byte[] ModificacionResult) {
            this.ModificacionResult = ModificacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inicial", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.InicialRequestBody Body;
        
        public InicialRequest() {
        }
        
        public InicialRequest(DeclaraINAI.Legacy.InicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class InicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public InicialRequestBody() {
        }
        
        public InicialRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InicialResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.InicialResponseBody Body;
        
        public InicialResponse() {
        }
        
        public InicialResponse(DeclaraINAI.Legacy.InicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class InicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] InicialResult;
        
        public InicialResponseBody() {
        }
        
        public InicialResponseBody(byte[] InicialResult) {
            this.InicialResult = InicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConclusionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conclusion", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ConclusionRequestBody Body;
        
        public ConclusionRequest() {
        }
        
        public ConclusionRequest(DeclaraINAI.Legacy.ConclusionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ConclusionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public ConclusionRequestBody() {
        }
        
        public ConclusionRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConclusionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConclusionResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ConclusionResponseBody Body;
        
        public ConclusionResponse() {
        }
        
        public ConclusionResponse(DeclaraINAI.Legacy.ConclusionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ConclusionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ConclusionResult;
        
        public ConclusionResponseBody() {
        }
        
        public ConclusionResponseBody(byte[] ConclusionResult) {
            this.ConclusionResult = ConclusionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Acuse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.AcuseRequestBody Body;
        
        public AcuseRequest() {
        }
        
        public AcuseRequest(DeclaraINAI.Legacy.AcuseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class AcuseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public AcuseRequestBody() {
        }
        
        public AcuseRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcuseResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.AcuseResponseBody Body;
        
        public AcuseResponse() {
        }
        
        public AcuseResponse(DeclaraINAI.Legacy.AcuseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class AcuseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] AcuseResult;
        
        public AcuseResponseBody() {
        }
        
        public AcuseResponseBody(byte[] AcuseResult) {
            this.AcuseResult = AcuseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResponsivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Responsiva", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ResponsivaRequestBody Body;
        
        public ResponsivaRequest() {
        }
        
        public ResponsivaRequest(DeclaraINAI.Legacy.ResponsivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ResponsivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        public ResponsivaRequestBody() {
        }
        
        public ResponsivaRequestBody(int NUM_EMPLEADO) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResponsivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResponsivaResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ResponsivaResponseBody Body;
        
        public ResponsivaResponse() {
        }
        
        public ResponsivaResponse(DeclaraINAI.Legacy.ResponsivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ResponsivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ResponsivaResult;
        
        public ResponsivaResponseBody() {
        }
        
        public ResponsivaResponseBody(byte[] ResponsivaResult) {
            this.ResponsivaResult = ResponsivaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadisticaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Estadistica", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.EstadisticaRequestBody Body;
        
        public EstadisticaRequest() {
        }
        
        public EstadisticaRequest(DeclaraINAI.Legacy.EstadisticaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class EstadisticaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CONTROL;
        
        public EstadisticaRequestBody() {
        }
        
        public EstadisticaRequestBody(int NUM_EMPLEADO, int CONTROL) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.CONTROL = CONTROL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadisticaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadisticaResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.EstadisticaResponseBody Body;
        
        public EstadisticaResponse() {
        }
        
        public EstadisticaResponse(DeclaraINAI.Legacy.EstadisticaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class EstadisticaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] EstadisticaResult;
        
        public EstadisticaResponseBody() {
        }
        
        public EstadisticaResponseBody(byte[] EstadisticaResult) {
            this.EstadisticaResult = EstadisticaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConflictoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conflicto", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ConflictoRequestBody Body;
        
        public ConflictoRequest() {
        }
        
        public ConflictoRequest(DeclaraINAI.Legacy.ConflictoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ConflictoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CONTROL;
        
        public ConflictoRequestBody() {
        }
        
        public ConflictoRequestBody(string Dia, int NUM_EMPLEADO, int CONTROL) {
            this.Dia = Dia;
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.CONTROL = CONTROL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConflictoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConflictoResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ConflictoResponseBody Body;
        
        public ConflictoResponse() {
        }
        
        public ConflictoResponse(DeclaraINAI.Legacy.ConflictoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ConflictoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ConflictoResult;
        
        public ConflictoResponseBody() {
        }
        
        public ConflictoResponseBody(byte[] ConflictoResult) {
            this.ConflictoResult = ConflictoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ConsultaRequestBody Body;
        
        public ConsultaRequest() {
        }
        
        public ConsultaRequest(DeclaraINAI.Legacy.ConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RFC;
        
        public ConsultaRequestBody() {
        }
        
        public ConsultaRequestBody(string RFC) {
            this.RFC = RFC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaResponse", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.ConsultaResponseBody Body;
        
        public ConsultaResponse() {
        }
        
        public ConsultaResponse(DeclaraINAI.Legacy.ConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class ConsultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DeclaraINAI.Legacy.ListaDeclara[] ConsultaResult;
        
        public ConsultaResponseBody() {
        }
        
        public ConsultaResponseBody(DeclaraINAI.Legacy.ListaDeclara[] ConsultaResult) {
            this.ConsultaResult = ConsultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta2010Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta2010", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.Consulta2010RequestBody Body;
        
        public Consulta2010Request() {
        }
        
        public Consulta2010Request(DeclaraINAI.Legacy.Consulta2010RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class Consulta2010RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RFC;
        
        public Consulta2010RequestBody() {
        }
        
        public Consulta2010RequestBody(string RFC) {
            this.RFC = RFC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta2010Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta2010Response", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.Consulta2010ResponseBody Body;
        
        public Consulta2010Response() {
        }
        
        public Consulta2010Response(DeclaraINAI.Legacy.Consulta2010ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class Consulta2010ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DeclaraINAI.Legacy.ListaAnt2010[] Consulta2010Result;
        
        public Consulta2010ResponseBody() {
        }
        
        public Consulta2010ResponseBody(DeclaraINAI.Legacy.ListaAnt2010[] Consulta2010Result) {
            this.Consulta2010Result = Consulta2010Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuseAnt2010Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcuseAnt2010", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.AcuseAnt2010RequestBody Body;
        
        public AcuseAnt2010Request() {
        }
        
        public AcuseAnt2010Request(DeclaraINAI.Legacy.AcuseAnt2010RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class AcuseAnt2010RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Archivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NOMARCH;
        
        public AcuseAnt2010RequestBody() {
        }
        
        public AcuseAnt2010RequestBody(string Archivo, string NOMARCH) {
            this.Archivo = Archivo;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuseAnt2010Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcuseAnt2010Response", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.AcuseAnt2010ResponseBody Body;
        
        public AcuseAnt2010Response() {
        }
        
        public AcuseAnt2010Response(DeclaraINAI.Legacy.AcuseAnt2010ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class AcuseAnt2010ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] AcuseAnt2010Result;
        
        public AcuseAnt2010ResponseBody() {
        }
        
        public AcuseAnt2010ResponseBody(byte[] AcuseAnt2010Result) {
            this.AcuseAnt2010Result = AcuseAnt2010Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeclaraAnt2010Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeclaraAnt2010", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.DeclaraAnt2010RequestBody Body;
        
        public DeclaraAnt2010Request() {
        }
        
        public DeclaraAnt2010Request(DeclaraINAI.Legacy.DeclaraAnt2010RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class DeclaraAnt2010RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Archivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NOMARCH;
        
        public DeclaraAnt2010RequestBody() {
        }
        
        public DeclaraAnt2010RequestBody(string Archivo, string NOMARCH) {
            this.Archivo = Archivo;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeclaraAnt2010Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeclaraAnt2010Response", Namespace="http://inai.mx/", Order=0)]
        public DeclaraINAI.Legacy.DeclaraAnt2010ResponseBody Body;
        
        public DeclaraAnt2010Response() {
        }
        
        public DeclaraAnt2010Response(DeclaraINAI.Legacy.DeclaraAnt2010ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://inai.mx/")]
    public partial class DeclaraAnt2010ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DeclaraAnt2010Result;
        
        public DeclaraAnt2010ResponseBody() {
        }
        
        public DeclaraAnt2010ResponseBody(byte[] DeclaraAnt2010Result) {
            this.DeclaraAnt2010Result = DeclaraAnt2010Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface fileSoapChannel : DeclaraINAI.Legacy.fileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fileSoapClient : System.ServiceModel.ClientBase<DeclaraINAI.Legacy.fileSoap>, DeclaraINAI.Legacy.fileSoap {
        
        public fileSoapClient() {
        }
        
        public fileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public fileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.TransparenciaResponse DeclaraINAI.Legacy.fileSoap.Transparencia(DeclaraINAI.Legacy.TransparenciaRequest request) {
            return base.Channel.Transparencia(request);
        }
        
        public byte[] Transparencia(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH, string ENVIADO, string FIMPRESION, string FEC_ENVIO) {
            DeclaraINAI.Legacy.TransparenciaRequest inValue = new DeclaraINAI.Legacy.TransparenciaRequest();
            inValue.Body = new DeclaraINAI.Legacy.TransparenciaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            inValue.Body.ENVIADO = ENVIADO;
            inValue.Body.FIMPRESION = FIMPRESION;
            inValue.Body.FEC_ENVIO = FEC_ENVIO;
            DeclaraINAI.Legacy.TransparenciaResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Transparencia(inValue);
            return retVal.Body.TransparenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.TransparenciaResponse> DeclaraINAI.Legacy.fileSoap.TransparenciaAsync(DeclaraINAI.Legacy.TransparenciaRequest request) {
            return base.Channel.TransparenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.TransparenciaResponse> TransparenciaAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH, string ENVIADO, string FIMPRESION, string FEC_ENVIO) {
            DeclaraINAI.Legacy.TransparenciaRequest inValue = new DeclaraINAI.Legacy.TransparenciaRequest();
            inValue.Body = new DeclaraINAI.Legacy.TransparenciaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            inValue.Body.ENVIADO = ENVIADO;
            inValue.Body.FIMPRESION = FIMPRESION;
            inValue.Body.FEC_ENVIO = FEC_ENVIO;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).TransparenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.ModificacionResponse DeclaraINAI.Legacy.fileSoap.Modificacion(DeclaraINAI.Legacy.ModificacionRequest request) {
            return base.Channel.Modificacion(request);
        }
        
        public byte[] Modificacion(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.ModificacionRequest inValue = new DeclaraINAI.Legacy.ModificacionRequest();
            inValue.Body = new DeclaraINAI.Legacy.ModificacionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINAI.Legacy.ModificacionResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Modificacion(inValue);
            return retVal.Body.ModificacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ModificacionResponse> DeclaraINAI.Legacy.fileSoap.ModificacionAsync(DeclaraINAI.Legacy.ModificacionRequest request) {
            return base.Channel.ModificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.ModificacionResponse> ModificacionAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.ModificacionRequest inValue = new DeclaraINAI.Legacy.ModificacionRequest();
            inValue.Body = new DeclaraINAI.Legacy.ModificacionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).ModificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.InicialResponse DeclaraINAI.Legacy.fileSoap.Inicial(DeclaraINAI.Legacy.InicialRequest request) {
            return base.Channel.Inicial(request);
        }
        
        public byte[] Inicial(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.InicialRequest inValue = new DeclaraINAI.Legacy.InicialRequest();
            inValue.Body = new DeclaraINAI.Legacy.InicialRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINAI.Legacy.InicialResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Inicial(inValue);
            return retVal.Body.InicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.InicialResponse> DeclaraINAI.Legacy.fileSoap.InicialAsync(DeclaraINAI.Legacy.InicialRequest request) {
            return base.Channel.InicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.InicialResponse> InicialAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.InicialRequest inValue = new DeclaraINAI.Legacy.InicialRequest();
            inValue.Body = new DeclaraINAI.Legacy.InicialRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).InicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.ConclusionResponse DeclaraINAI.Legacy.fileSoap.Conclusion(DeclaraINAI.Legacy.ConclusionRequest request) {
            return base.Channel.Conclusion(request);
        }
        
        public byte[] Conclusion(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.ConclusionRequest inValue = new DeclaraINAI.Legacy.ConclusionRequest();
            inValue.Body = new DeclaraINAI.Legacy.ConclusionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINAI.Legacy.ConclusionResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Conclusion(inValue);
            return retVal.Body.ConclusionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConclusionResponse> DeclaraINAI.Legacy.fileSoap.ConclusionAsync(DeclaraINAI.Legacy.ConclusionRequest request) {
            return base.Channel.ConclusionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConclusionResponse> ConclusionAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.ConclusionRequest inValue = new DeclaraINAI.Legacy.ConclusionRequest();
            inValue.Body = new DeclaraINAI.Legacy.ConclusionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).ConclusionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.AcuseResponse DeclaraINAI.Legacy.fileSoap.Acuse(DeclaraINAI.Legacy.AcuseRequest request) {
            return base.Channel.Acuse(request);
        }
        
        public byte[] Acuse(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.AcuseRequest inValue = new DeclaraINAI.Legacy.AcuseRequest();
            inValue.Body = new DeclaraINAI.Legacy.AcuseRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINAI.Legacy.AcuseResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Acuse(inValue);
            return retVal.Body.AcuseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.AcuseResponse> DeclaraINAI.Legacy.fileSoap.AcuseAsync(DeclaraINAI.Legacy.AcuseRequest request) {
            return base.Channel.AcuseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.AcuseResponse> AcuseAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINAI.Legacy.AcuseRequest inValue = new DeclaraINAI.Legacy.AcuseRequest();
            inValue.Body = new DeclaraINAI.Legacy.AcuseRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).AcuseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.ResponsivaResponse DeclaraINAI.Legacy.fileSoap.Responsiva(DeclaraINAI.Legacy.ResponsivaRequest request) {
            return base.Channel.Responsiva(request);
        }
        
        public byte[] Responsiva(int NUM_EMPLEADO) {
            DeclaraINAI.Legacy.ResponsivaRequest inValue = new DeclaraINAI.Legacy.ResponsivaRequest();
            inValue.Body = new DeclaraINAI.Legacy.ResponsivaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            DeclaraINAI.Legacy.ResponsivaResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Responsiva(inValue);
            return retVal.Body.ResponsivaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ResponsivaResponse> DeclaraINAI.Legacy.fileSoap.ResponsivaAsync(DeclaraINAI.Legacy.ResponsivaRequest request) {
            return base.Channel.ResponsivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.ResponsivaResponse> ResponsivaAsync(int NUM_EMPLEADO) {
            DeclaraINAI.Legacy.ResponsivaRequest inValue = new DeclaraINAI.Legacy.ResponsivaRequest();
            inValue.Body = new DeclaraINAI.Legacy.ResponsivaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).ResponsivaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.EstadisticaResponse DeclaraINAI.Legacy.fileSoap.Estadistica(DeclaraINAI.Legacy.EstadisticaRequest request) {
            return base.Channel.Estadistica(request);
        }
        
        public byte[] Estadistica(int NUM_EMPLEADO, int CONTROL) {
            DeclaraINAI.Legacy.EstadisticaRequest inValue = new DeclaraINAI.Legacy.EstadisticaRequest();
            inValue.Body = new DeclaraINAI.Legacy.EstadisticaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            DeclaraINAI.Legacy.EstadisticaResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Estadistica(inValue);
            return retVal.Body.EstadisticaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.EstadisticaResponse> DeclaraINAI.Legacy.fileSoap.EstadisticaAsync(DeclaraINAI.Legacy.EstadisticaRequest request) {
            return base.Channel.EstadisticaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.EstadisticaResponse> EstadisticaAsync(int NUM_EMPLEADO, int CONTROL) {
            DeclaraINAI.Legacy.EstadisticaRequest inValue = new DeclaraINAI.Legacy.EstadisticaRequest();
            inValue.Body = new DeclaraINAI.Legacy.EstadisticaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).EstadisticaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.ConflictoResponse DeclaraINAI.Legacy.fileSoap.Conflicto(DeclaraINAI.Legacy.ConflictoRequest request) {
            return base.Channel.Conflicto(request);
        }
        
        public byte[] Conflicto(string Dia, int NUM_EMPLEADO, int CONTROL) {
            DeclaraINAI.Legacy.ConflictoRequest inValue = new DeclaraINAI.Legacy.ConflictoRequest();
            inValue.Body = new DeclaraINAI.Legacy.ConflictoRequestBody();
            inValue.Body.Dia = Dia;
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            DeclaraINAI.Legacy.ConflictoResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Conflicto(inValue);
            return retVal.Body.ConflictoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConflictoResponse> DeclaraINAI.Legacy.fileSoap.ConflictoAsync(DeclaraINAI.Legacy.ConflictoRequest request) {
            return base.Channel.ConflictoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConflictoResponse> ConflictoAsync(string Dia, int NUM_EMPLEADO, int CONTROL) {
            DeclaraINAI.Legacy.ConflictoRequest inValue = new DeclaraINAI.Legacy.ConflictoRequest();
            inValue.Body = new DeclaraINAI.Legacy.ConflictoRequestBody();
            inValue.Body.Dia = Dia;
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).ConflictoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.ConsultaResponse DeclaraINAI.Legacy.fileSoap.Consulta(DeclaraINAI.Legacy.ConsultaRequest request) {
            return base.Channel.Consulta(request);
        }
        
        public DeclaraINAI.Legacy.ListaDeclara[] Consulta(string RFC) {
            DeclaraINAI.Legacy.ConsultaRequest inValue = new DeclaraINAI.Legacy.ConsultaRequest();
            inValue.Body = new DeclaraINAI.Legacy.ConsultaRequestBody();
            inValue.Body.RFC = RFC;
            DeclaraINAI.Legacy.ConsultaResponse retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Consulta(inValue);
            return retVal.Body.ConsultaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConsultaResponse> DeclaraINAI.Legacy.fileSoap.ConsultaAsync(DeclaraINAI.Legacy.ConsultaRequest request) {
            return base.Channel.ConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.ConsultaResponse> ConsultaAsync(string RFC) {
            DeclaraINAI.Legacy.ConsultaRequest inValue = new DeclaraINAI.Legacy.ConsultaRequest();
            inValue.Body = new DeclaraINAI.Legacy.ConsultaRequestBody();
            inValue.Body.RFC = RFC;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).ConsultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.Consulta2010Response DeclaraINAI.Legacy.fileSoap.Consulta2010(DeclaraINAI.Legacy.Consulta2010Request request) {
            return base.Channel.Consulta2010(request);
        }
        
        public DeclaraINAI.Legacy.ListaAnt2010[] Consulta2010(string RFC) {
            DeclaraINAI.Legacy.Consulta2010Request inValue = new DeclaraINAI.Legacy.Consulta2010Request();
            inValue.Body = new DeclaraINAI.Legacy.Consulta2010RequestBody();
            inValue.Body.RFC = RFC;
            DeclaraINAI.Legacy.Consulta2010Response retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).Consulta2010(inValue);
            return retVal.Body.Consulta2010Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.Consulta2010Response> DeclaraINAI.Legacy.fileSoap.Consulta2010Async(DeclaraINAI.Legacy.Consulta2010Request request) {
            return base.Channel.Consulta2010Async(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.Consulta2010Response> Consulta2010Async(string RFC) {
            DeclaraINAI.Legacy.Consulta2010Request inValue = new DeclaraINAI.Legacy.Consulta2010Request();
            inValue.Body = new DeclaraINAI.Legacy.Consulta2010RequestBody();
            inValue.Body.RFC = RFC;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).Consulta2010Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.AcuseAnt2010Response DeclaraINAI.Legacy.fileSoap.AcuseAnt2010(DeclaraINAI.Legacy.AcuseAnt2010Request request) {
            return base.Channel.AcuseAnt2010(request);
        }
        
        public byte[] AcuseAnt2010(string Archivo, string NOMARCH) {
            DeclaraINAI.Legacy.AcuseAnt2010Request inValue = new DeclaraINAI.Legacy.AcuseAnt2010Request();
            inValue.Body = new DeclaraINAI.Legacy.AcuseAnt2010RequestBody();
            inValue.Body.Archivo = Archivo;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINAI.Legacy.AcuseAnt2010Response retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).AcuseAnt2010(inValue);
            return retVal.Body.AcuseAnt2010Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.AcuseAnt2010Response> DeclaraINAI.Legacy.fileSoap.AcuseAnt2010Async(DeclaraINAI.Legacy.AcuseAnt2010Request request) {
            return base.Channel.AcuseAnt2010Async(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.AcuseAnt2010Response> AcuseAnt2010Async(string Archivo, string NOMARCH) {
            DeclaraINAI.Legacy.AcuseAnt2010Request inValue = new DeclaraINAI.Legacy.AcuseAnt2010Request();
            inValue.Body = new DeclaraINAI.Legacy.AcuseAnt2010RequestBody();
            inValue.Body.Archivo = Archivo;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).AcuseAnt2010Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINAI.Legacy.DeclaraAnt2010Response DeclaraINAI.Legacy.fileSoap.DeclaraAnt2010(DeclaraINAI.Legacy.DeclaraAnt2010Request request) {
            return base.Channel.DeclaraAnt2010(request);
        }
        
        public byte[] DeclaraAnt2010(string Archivo, string NOMARCH) {
            DeclaraINAI.Legacy.DeclaraAnt2010Request inValue = new DeclaraINAI.Legacy.DeclaraAnt2010Request();
            inValue.Body = new DeclaraINAI.Legacy.DeclaraAnt2010RequestBody();
            inValue.Body.Archivo = Archivo;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINAI.Legacy.DeclaraAnt2010Response retVal = ((DeclaraINAI.Legacy.fileSoap)(this)).DeclaraAnt2010(inValue);
            return retVal.Body.DeclaraAnt2010Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINAI.Legacy.DeclaraAnt2010Response> DeclaraINAI.Legacy.fileSoap.DeclaraAnt2010Async(DeclaraINAI.Legacy.DeclaraAnt2010Request request) {
            return base.Channel.DeclaraAnt2010Async(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINAI.Legacy.DeclaraAnt2010Response> DeclaraAnt2010Async(string Archivo, string NOMARCH) {
            DeclaraINAI.Legacy.DeclaraAnt2010Request inValue = new DeclaraINAI.Legacy.DeclaraAnt2010Request();
            inValue.Body = new DeclaraINAI.Legacy.DeclaraAnt2010RequestBody();
            inValue.Body.Archivo = Archivo;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINAI.Legacy.fileSoap)(this)).DeclaraAnt2010Async(inValue);
        }
    }
}
