//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeclaraINEAdmin.Legacy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeclara", Namespace="http://ine.mx/")]
    [System.SerializableAttribute()]
    public partial class ListaDeclara : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Num_EmpleadoField;
        
        private int ID_DeclaraField;
        
        private int T_DField;
        
        private int AnioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Hora_EnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fec_EnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_T_DField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClasificaField;
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Num_Empleado {
            get {
                return this.Num_EmpleadoField;
            }
            set {
                if ((this.Num_EmpleadoField.Equals(value) != true)) {
                    this.Num_EmpleadoField = value;
                    this.RaisePropertyChanged("Num_Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_Declara {
            get {
                return this.ID_DeclaraField;
            }
            set {
                if ((this.ID_DeclaraField.Equals(value) != true)) {
                    this.ID_DeclaraField = value;
                    this.RaisePropertyChanged("ID_Declara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int T_D {
            get {
                return this.T_DField;
            }
            set {
                if ((this.T_DField.Equals(value) != true)) {
                    this.T_DField = value;
                    this.RaisePropertyChanged("T_D");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Anio {
            get {
                return this.AnioField;
            }
            set {
                if ((this.AnioField.Equals(value) != true)) {
                    this.AnioField = value;
                    this.RaisePropertyChanged("Anio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Hora_Envio {
            get {
                return this.Hora_EnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.Hora_EnvioField, value) != true)) {
                    this.Hora_EnvioField = value;
                    this.RaisePropertyChanged("Hora_Envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Fec_Envio {
            get {
                return this.Fec_EnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.Fec_EnvioField, value) != true)) {
                    this.Fec_EnvioField = value;
                    this.RaisePropertyChanged("Fec_Envio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Desc_T_D {
            get {
                return this.Desc_T_DField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_T_DField, value) != true)) {
                    this.Desc_T_DField = value;
                    this.RaisePropertyChanged("Desc_T_D");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public int Clasifica
        {
            get
            {
                return this.ClasificaField;
            }
            set
            {
                if ((this.ClasificaField.Equals(value) != true))
                {
                    this.ClasificaField = value;
                    this.RaisePropertyChanged("Clasifica");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ine.mx/", ConfigurationName="Legacy.fileSoap")]
    public interface fileSoap {
        
        // CODEGEN: Generating message contract since element name NOMARCH from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Transparencia", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.TransparenciaResponse Transparencia(DeclaraINEAdmin.Legacy.TransparenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Transparencia", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.TransparenciaResponse> TransparenciaAsync(DeclaraINEAdmin.Legacy.TransparenciaRequest request);
        
        // CODEGEN: Generating message contract since element name NOMARCH from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Modificacion", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.ModificacionResponse Modificacion(DeclaraINEAdmin.Legacy.ModificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Modificacion", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ModificacionResponse> ModificacionAsync(DeclaraINEAdmin.Legacy.ModificacionRequest request);
        
        // CODEGEN: Generating message contract since element name NOMARCH from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Inicial", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.InicialResponse Inicial(DeclaraINEAdmin.Legacy.InicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Inicial", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.InicialResponse> InicialAsync(DeclaraINEAdmin.Legacy.InicialRequest request);
        
        // CODEGEN: Generating message contract since element name NOMARCH from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Conclusion", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.ConclusionResponse Conclusion(DeclaraINEAdmin.Legacy.ConclusionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Conclusion", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConclusionResponse> ConclusionAsync(DeclaraINEAdmin.Legacy.ConclusionRequest request);
        
        // CODEGEN: Generating message contract since element name NOMARCH from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Acuse", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.AcuseResponse Acuse(DeclaraINEAdmin.Legacy.AcuseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Acuse", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.AcuseResponse> AcuseAsync(DeclaraINEAdmin.Legacy.AcuseRequest request);
        
        // CODEGEN: Generating message contract since element name ResponsivaResult from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Responsiva", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.ResponsivaResponse Responsiva(DeclaraINEAdmin.Legacy.ResponsivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Responsiva", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ResponsivaResponse> ResponsivaAsync(DeclaraINEAdmin.Legacy.ResponsivaRequest request);
        
        // CODEGEN: Generating message contract since element name EstadisticaResult from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Estadistica", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.EstadisticaResponse Estadistica(DeclaraINEAdmin.Legacy.EstadisticaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Estadistica", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.EstadisticaResponse> EstadisticaAsync(DeclaraINEAdmin.Legacy.EstadisticaRequest request);
        
        // CODEGEN: Generating message contract since element name Dia from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Conflicto", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.ConflictoResponse Conflicto(DeclaraINEAdmin.Legacy.ConflictoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Conflicto", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConflictoResponse> ConflictoAsync(DeclaraINEAdmin.Legacy.ConflictoRequest request);
        
        // CODEGEN: Generating message contract since element name RFC from namespace http://ine.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Consulta", ReplyAction="*")]
        DeclaraINEAdmin.Legacy.ConsultaResponse Consulta(DeclaraINEAdmin.Legacy.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ine.mx/Consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConsultaResponse> ConsultaAsync(DeclaraINEAdmin.Legacy.ConsultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransparenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Transparencia", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.TransparenciaRequestBody Body;
        
        public TransparenciaRequest() {
        }
        
        public TransparenciaRequest(DeclaraINEAdmin.Legacy.TransparenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class TransparenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ENVIADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FIMPRESION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FEC_ENVIO;
        
        public TransparenciaRequestBody() {
        }
        
        public TransparenciaRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH, string ENVIADO, string FIMPRESION, string FEC_ENVIO) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
            this.ENVIADO = ENVIADO;
            this.FIMPRESION = FIMPRESION;
            this.FEC_ENVIO = FEC_ENVIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransparenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransparenciaResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.TransparenciaResponseBody Body;
        
        public TransparenciaResponse() {
        }
        
        public TransparenciaResponse(DeclaraINEAdmin.Legacy.TransparenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class TransparenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TransparenciaResult;
        
        public TransparenciaResponseBody() {
        }
        
        public TransparenciaResponseBody(byte[] TransparenciaResult) {
            this.TransparenciaResult = TransparenciaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificacion", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ModificacionRequestBody Body;
        
        public ModificacionRequest() {
        }
        
        public ModificacionRequest(DeclaraINEAdmin.Legacy.ModificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ModificacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public ModificacionRequestBody() {
        }
        
        public ModificacionRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificacionResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ModificacionResponseBody Body;
        
        public ModificacionResponse() {
        }
        
        public ModificacionResponse(DeclaraINEAdmin.Legacy.ModificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ModificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ModificacionResult;
        
        public ModificacionResponseBody() {
        }
        
        public ModificacionResponseBody(byte[] ModificacionResult) {
            this.ModificacionResult = ModificacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inicial", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.InicialRequestBody Body;
        
        public InicialRequest() {
        }
        
        public InicialRequest(DeclaraINEAdmin.Legacy.InicialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class InicialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public InicialRequestBody() {
        }
        
        public InicialRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InicialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InicialResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.InicialResponseBody Body;
        
        public InicialResponse() {
        }
        
        public InicialResponse(DeclaraINEAdmin.Legacy.InicialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class InicialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] InicialResult;
        
        public InicialResponseBody() {
        }
        
        public InicialResponseBody(byte[] InicialResult) {
            this.InicialResult = InicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConclusionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conclusion", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ConclusionRequestBody Body;
        
        public ConclusionRequest() {
        }
        
        public ConclusionRequest(DeclaraINEAdmin.Legacy.ConclusionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ConclusionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public ConclusionRequestBody() {
        }
        
        public ConclusionRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConclusionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConclusionResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ConclusionResponseBody Body;
        
        public ConclusionResponse() {
        }
        
        public ConclusionResponse(DeclaraINEAdmin.Legacy.ConclusionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ConclusionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ConclusionResult;
        
        public ConclusionResponseBody() {
        }
        
        public ConclusionResponseBody(byte[] ConclusionResult) {
            this.ConclusionResult = ConclusionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Acuse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.AcuseRequestBody Body;
        
        public AcuseRequest() {
        }
        
        public AcuseRequest(DeclaraINEAdmin.Legacy.AcuseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class AcuseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID_DECLARA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int T_D;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ANIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NOMARCH;
        
        public AcuseRequestBody() {
        }
        
        public AcuseRequestBody(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.ID_DECLARA = ID_DECLARA;
            this.T_D = T_D;
            this.ANIO = ANIO;
            this.NOMARCH = NOMARCH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AcuseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AcuseResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.AcuseResponseBody Body;
        
        public AcuseResponse() {
        }
        
        public AcuseResponse(DeclaraINEAdmin.Legacy.AcuseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class AcuseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] AcuseResult;
        
        public AcuseResponseBody() {
        }
        
        public AcuseResponseBody(byte[] AcuseResult) {
            this.AcuseResult = AcuseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResponsivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Responsiva", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ResponsivaRequestBody Body;
        
        public ResponsivaRequest() {
        }
        
        public ResponsivaRequest(DeclaraINEAdmin.Legacy.ResponsivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ResponsivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        public ResponsivaRequestBody() {
        }
        
        public ResponsivaRequestBody(int NUM_EMPLEADO) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResponsivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResponsivaResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ResponsivaResponseBody Body;
        
        public ResponsivaResponse() {
        }
        
        public ResponsivaResponse(DeclaraINEAdmin.Legacy.ResponsivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ResponsivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ResponsivaResult;
        
        public ResponsivaResponseBody() {
        }
        
        public ResponsivaResponseBody(byte[] ResponsivaResult) {
            this.ResponsivaResult = ResponsivaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadisticaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Estadistica", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.EstadisticaRequestBody Body;
        
        public EstadisticaRequest() {
        }
        
        public EstadisticaRequest(DeclaraINEAdmin.Legacy.EstadisticaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class EstadisticaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CONTROL;
        
        public EstadisticaRequestBody() {
        }
        
        public EstadisticaRequestBody(int NUM_EMPLEADO, int CONTROL) {
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.CONTROL = CONTROL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadisticaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadisticaResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.EstadisticaResponseBody Body;
        
        public EstadisticaResponse() {
        }
        
        public EstadisticaResponse(DeclaraINEAdmin.Legacy.EstadisticaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class EstadisticaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] EstadisticaResult;
        
        public EstadisticaResponseBody() {
        }
        
        public EstadisticaResponseBody(byte[] EstadisticaResult) {
            this.EstadisticaResult = EstadisticaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConflictoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Conflicto", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ConflictoRequestBody Body;
        
        public ConflictoRequest() {
        }
        
        public ConflictoRequest(DeclaraINEAdmin.Legacy.ConflictoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ConflictoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int NUM_EMPLEADO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CONTROL;
        
        public ConflictoRequestBody() {
        }
        
        public ConflictoRequestBody(string Dia, int NUM_EMPLEADO, int CONTROL) {
            this.Dia = Dia;
            this.NUM_EMPLEADO = NUM_EMPLEADO;
            this.CONTROL = CONTROL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConflictoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConflictoResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ConflictoResponseBody Body;
        
        public ConflictoResponse() {
        }
        
        public ConflictoResponse(DeclaraINEAdmin.Legacy.ConflictoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ConflictoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ConflictoResult;
        
        public ConflictoResponseBody() {
        }
        
        public ConflictoResponseBody(byte[] ConflictoResult) {
            this.ConflictoResult = ConflictoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ConsultaRequestBody Body;
        
        public ConsultaRequest() {
        }
        
        public ConsultaRequest(DeclaraINEAdmin.Legacy.ConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RFC;
        
        public ConsultaRequestBody() {
        }
        
        public ConsultaRequestBody(string RFC) {
            this.RFC = RFC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaResponse", Namespace="http://ine.mx/", Order=0)]
        public DeclaraINEAdmin.Legacy.ConsultaResponseBody Body;
        
        public ConsultaResponse() {
        }
        
        public ConsultaResponse(DeclaraINEAdmin.Legacy.ConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ine.mx/")]
    public partial class ConsultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DeclaraINEAdmin.Legacy.ListaDeclara[] ConsultaResult;
        
        public ConsultaResponseBody() {
        }
        
        public ConsultaResponseBody(DeclaraINEAdmin.Legacy.ListaDeclara[] ConsultaResult) {
            this.ConsultaResult = ConsultaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface fileSoapChannel : DeclaraINEAdmin.Legacy.fileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class fileSoapClient : System.ServiceModel.ClientBase<DeclaraINEAdmin.Legacy.fileSoap>, DeclaraINEAdmin.Legacy.fileSoap {
        
        public fileSoapClient() {
        }
        
        public fileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public fileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public fileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.TransparenciaResponse DeclaraINEAdmin.Legacy.fileSoap.Transparencia(DeclaraINEAdmin.Legacy.TransparenciaRequest request) {
            return base.Channel.Transparencia(request);
        }
        
        public byte[] Transparencia(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH, string ENVIADO, string FIMPRESION, string FEC_ENVIO) {
            DeclaraINEAdmin.Legacy.TransparenciaRequest inValue = new DeclaraINEAdmin.Legacy.TransparenciaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.TransparenciaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            inValue.Body.ENVIADO = ENVIADO;
            inValue.Body.FIMPRESION = FIMPRESION;
            inValue.Body.FEC_ENVIO = FEC_ENVIO;
            DeclaraINEAdmin.Legacy.TransparenciaResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Transparencia(inValue);
            return retVal.Body.TransparenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.TransparenciaResponse> DeclaraINEAdmin.Legacy.fileSoap.TransparenciaAsync(DeclaraINEAdmin.Legacy.TransparenciaRequest request) {
            return base.Channel.TransparenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.TransparenciaResponse> TransparenciaAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH, string ENVIADO, string FIMPRESION, string FEC_ENVIO) {
            DeclaraINEAdmin.Legacy.TransparenciaRequest inValue = new DeclaraINEAdmin.Legacy.TransparenciaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.TransparenciaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            inValue.Body.ENVIADO = ENVIADO;
            inValue.Body.FIMPRESION = FIMPRESION;
            inValue.Body.FEC_ENVIO = FEC_ENVIO;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).TransparenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.ModificacionResponse DeclaraINEAdmin.Legacy.fileSoap.Modificacion(DeclaraINEAdmin.Legacy.ModificacionRequest request) {
            return base.Channel.Modificacion(request);
        }
        
        public byte[] Modificacion(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.ModificacionRequest inValue = new DeclaraINEAdmin.Legacy.ModificacionRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ModificacionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINEAdmin.Legacy.ModificacionResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Modificacion(inValue);
            return retVal.Body.ModificacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ModificacionResponse> DeclaraINEAdmin.Legacy.fileSoap.ModificacionAsync(DeclaraINEAdmin.Legacy.ModificacionRequest request) {
            return base.Channel.ModificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ModificacionResponse> ModificacionAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.ModificacionRequest inValue = new DeclaraINEAdmin.Legacy.ModificacionRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ModificacionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).ModificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.InicialResponse DeclaraINEAdmin.Legacy.fileSoap.Inicial(DeclaraINEAdmin.Legacy.InicialRequest request) {
            return base.Channel.Inicial(request);
        }
        
        public byte[] Inicial(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.InicialRequest inValue = new DeclaraINEAdmin.Legacy.InicialRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.InicialRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINEAdmin.Legacy.InicialResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Inicial(inValue);
            return retVal.Body.InicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.InicialResponse> DeclaraINEAdmin.Legacy.fileSoap.InicialAsync(DeclaraINEAdmin.Legacy.InicialRequest request) {
            return base.Channel.InicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.InicialResponse> InicialAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.InicialRequest inValue = new DeclaraINEAdmin.Legacy.InicialRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.InicialRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).InicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.ConclusionResponse DeclaraINEAdmin.Legacy.fileSoap.Conclusion(DeclaraINEAdmin.Legacy.ConclusionRequest request) {
            return base.Channel.Conclusion(request);
        }
        
        public byte[] Conclusion(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.ConclusionRequest inValue = new DeclaraINEAdmin.Legacy.ConclusionRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ConclusionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINEAdmin.Legacy.ConclusionResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Conclusion(inValue);
            return retVal.Body.ConclusionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConclusionResponse> DeclaraINEAdmin.Legacy.fileSoap.ConclusionAsync(DeclaraINEAdmin.Legacy.ConclusionRequest request) {
            return base.Channel.ConclusionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConclusionResponse> ConclusionAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.ConclusionRequest inValue = new DeclaraINEAdmin.Legacy.ConclusionRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ConclusionRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).ConclusionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.AcuseResponse DeclaraINEAdmin.Legacy.fileSoap.Acuse(DeclaraINEAdmin.Legacy.AcuseRequest request) {
            return base.Channel.Acuse(request);
        }
        
        public byte[] Acuse(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.AcuseRequest inValue = new DeclaraINEAdmin.Legacy.AcuseRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.AcuseRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            DeclaraINEAdmin.Legacy.AcuseResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Acuse(inValue);
            return retVal.Body.AcuseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.AcuseResponse> DeclaraINEAdmin.Legacy.fileSoap.AcuseAsync(DeclaraINEAdmin.Legacy.AcuseRequest request) {
            return base.Channel.AcuseAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.AcuseResponse> AcuseAsync(int NUM_EMPLEADO, int ID_DECLARA, int T_D, int ANIO, string NOMARCH) {
            DeclaraINEAdmin.Legacy.AcuseRequest inValue = new DeclaraINEAdmin.Legacy.AcuseRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.AcuseRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.ID_DECLARA = ID_DECLARA;
            inValue.Body.T_D = T_D;
            inValue.Body.ANIO = ANIO;
            inValue.Body.NOMARCH = NOMARCH;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).AcuseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.ResponsivaResponse DeclaraINEAdmin.Legacy.fileSoap.Responsiva(DeclaraINEAdmin.Legacy.ResponsivaRequest request) {
            return base.Channel.Responsiva(request);
        }
        
        public byte[] Responsiva(int NUM_EMPLEADO) {
            DeclaraINEAdmin.Legacy.ResponsivaRequest inValue = new DeclaraINEAdmin.Legacy.ResponsivaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ResponsivaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            DeclaraINEAdmin.Legacy.ResponsivaResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Responsiva(inValue);
            return retVal.Body.ResponsivaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ResponsivaResponse> DeclaraINEAdmin.Legacy.fileSoap.ResponsivaAsync(DeclaraINEAdmin.Legacy.ResponsivaRequest request) {
            return base.Channel.ResponsivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ResponsivaResponse> ResponsivaAsync(int NUM_EMPLEADO) {
            DeclaraINEAdmin.Legacy.ResponsivaRequest inValue = new DeclaraINEAdmin.Legacy.ResponsivaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ResponsivaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).ResponsivaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.EstadisticaResponse DeclaraINEAdmin.Legacy.fileSoap.Estadistica(DeclaraINEAdmin.Legacy.EstadisticaRequest request) {
            return base.Channel.Estadistica(request);
        }
        
        public byte[] Estadistica(int NUM_EMPLEADO, int CONTROL) {
            DeclaraINEAdmin.Legacy.EstadisticaRequest inValue = new DeclaraINEAdmin.Legacy.EstadisticaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.EstadisticaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            DeclaraINEAdmin.Legacy.EstadisticaResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Estadistica(inValue);
            return retVal.Body.EstadisticaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.EstadisticaResponse> DeclaraINEAdmin.Legacy.fileSoap.EstadisticaAsync(DeclaraINEAdmin.Legacy.EstadisticaRequest request) {
            return base.Channel.EstadisticaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.EstadisticaResponse> EstadisticaAsync(int NUM_EMPLEADO, int CONTROL) {
            DeclaraINEAdmin.Legacy.EstadisticaRequest inValue = new DeclaraINEAdmin.Legacy.EstadisticaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.EstadisticaRequestBody();
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).EstadisticaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.ConflictoResponse DeclaraINEAdmin.Legacy.fileSoap.Conflicto(DeclaraINEAdmin.Legacy.ConflictoRequest request) {
            return base.Channel.Conflicto(request);
        }
        
        public byte[] Conflicto(string Dia, int NUM_EMPLEADO, int CONTROL) {
            DeclaraINEAdmin.Legacy.ConflictoRequest inValue = new DeclaraINEAdmin.Legacy.ConflictoRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ConflictoRequestBody();
            inValue.Body.Dia = Dia;
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            DeclaraINEAdmin.Legacy.ConflictoResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Conflicto(inValue);
            return retVal.Body.ConflictoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConflictoResponse> DeclaraINEAdmin.Legacy.fileSoap.ConflictoAsync(DeclaraINEAdmin.Legacy.ConflictoRequest request) {
            return base.Channel.ConflictoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConflictoResponse> ConflictoAsync(string Dia, int NUM_EMPLEADO, int CONTROL) {
            DeclaraINEAdmin.Legacy.ConflictoRequest inValue = new DeclaraINEAdmin.Legacy.ConflictoRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ConflictoRequestBody();
            inValue.Body.Dia = Dia;
            inValue.Body.NUM_EMPLEADO = NUM_EMPLEADO;
            inValue.Body.CONTROL = CONTROL;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).ConflictoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeclaraINEAdmin.Legacy.ConsultaResponse DeclaraINEAdmin.Legacy.fileSoap.Consulta(DeclaraINEAdmin.Legacy.ConsultaRequest request) {
            return base.Channel.Consulta(request);
        }
        
        public DeclaraINEAdmin.Legacy.ListaDeclara[] Consulta(string RFC) {
            DeclaraINEAdmin.Legacy.ConsultaRequest inValue = new DeclaraINEAdmin.Legacy.ConsultaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ConsultaRequestBody();
            inValue.Body.RFC = RFC;
            DeclaraINEAdmin.Legacy.ConsultaResponse retVal = ((DeclaraINEAdmin.Legacy.fileSoap)(this)).Consulta(inValue);
            return retVal.Body.ConsultaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConsultaResponse> DeclaraINEAdmin.Legacy.fileSoap.ConsultaAsync(DeclaraINEAdmin.Legacy.ConsultaRequest request) {
            return base.Channel.ConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeclaraINEAdmin.Legacy.ConsultaResponse> ConsultaAsync(string RFC) {
            DeclaraINEAdmin.Legacy.ConsultaRequest inValue = new DeclaraINEAdmin.Legacy.ConsultaRequest();
            inValue.Body = new DeclaraINEAdmin.Legacy.ConsultaRequestBody();
            inValue.Body.RFC = RFC;
            return ((DeclaraINEAdmin.Legacy.fileSoap)(this)).ConsultaAsync(inValue);
        }
    }
}
